### ISSUE TITLE
Chrome web-app standards

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#101]
### Warframe Hub Issue
---

**Summary (short):** Perhaps [this](https://developers.google.com/web/fundamentals/app-install-banners/) is something to shoot for to make it easier for mobile users?

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by CMDadabo** [comment]
That would be great! Looks like we have some work to do:

![Lighthouse Audit Results](https://cdn.pbrd.co/images/Hdf5Kvf.png)

**Comment by TobiTenno** [comment]
yeah, sadly loading that much data tends to not be the most... performance efficient.

**Comment by EricSihaoLin** [comment]
Those are some unfortunately numbers if I do say so myself...

**Comment by dsinn** [comment]
After #163:

![screenshot 2018-08-14 11 20 56](https://user-images.githubusercontent.com/5075438/44101280-0fd04d7a-9fb5-11e8-9f9c-b6171d8d4168.png)

**Comment by dsinn** [comment]
With #169:

<img width="483" alt="screenshot 2018-08-18 15 15 22" src="https://user-images.githubusercontent.com/5075438/44302622-12c21380-a2fb-11e8-90ad-191872cf4b7b.png">

**Comment by dsinn** [comment]
Accidentally closed this with the commit message in #169

**Comment by TobiTenno** [comment]
Performance has definitely gone down, others are better

![image](https://user-images.githubusercontent.com/7128721/97830485-c0c6f780-1c92-11eb-959f-ee63b50afb36.png)

**Comment by TobiTenno** [comment]
i feel like performance will always be kinda... meh due to the amount of stuff and it only judges first load, which is when we load, ya know, a ton
