### ISSUE TITLE
Theme Switching Not Working on Fish Data Page

### ISSUE THREAD

**Issue by EricSihaoLin** [WFCD/warframe-hub#102]
### Warframe Hub Issue
---

**Summary (short):**
---

As title suggests, if you are on the fishing data page: https://hub.warframestat.us/fish, none of the theme switcher works as intended.

**Description:**

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
oh, i think i know why...
