### ISSUE TITLE
Hover over fish parts does not display popup in Retro Theme

### ISSUE THREAD

**Issue by EricSihaoLin** [WFCD/warframe-hub#104]
### Warframe Hub Issue
---

**Summary (short):**
---

The hover to see picture of the part in the fishing data page does not work properly in the Retro theme.

**Description:**

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
fixed
