### ISSUE TITLE
:bug: No details about bounties for any of the worlds "Pattern Mismatch. Results inaccurate."

### ISSUE THREAD

**Issue by braiam** [WFCD/warframe-hub#1075]
### Summary

The details of the bounties, rewards and type, are empty. Tested on iOS and Firefox desktop. I'm not sure if the API should be providing these. Console is empty. Only message is "Pattern Mismatch. Results inaccurate."

### Version

hub (Default)

### What browsers are you seeing the problem on?

Firefox, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by braiam** [comment]
Well, sometimes it show that message, other times it shows nothing. Other rare cases, it shows you for a couple of bounties. Very inconsistent.

**Comment by TobiTenno** [comment]
looks like they synced back up.... i can't say why some wouldn't. if you see some, feel free to comment, and grab the data from https://api.warframestat.us/pc/syndicateMissions/?language=en and pop it in a comment here and i'll investigate from there
