### ISSUE TITLE
Orbiter News shows messages out of order

### ISSUE THREAD

**Issue by EricSihaoLin** [WFCD/warframe-hub#108]
### Warframe Hub Issue
---

**Summary (short):**
---

See screenshot, the duration are out of order.

**Description:**
---

**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**
---

![image](https://user-images.githubusercontent.com/1594432/39079361-c06428c0-44e6-11e8-8ae0-f5f1d5643aa5.png)

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
clarified: it's because of prioritization
