### ISSUE TITLE
Sound notification

### ISSUE THREAD

**Issue by DarthDraconis91** [WFCD/warframe-hub#1147]
### Summary

i have setup to get notified for when cetus/plains of eidolon becomes night along with enabling sound for the notification yet the sound notification never happens

### Version

hub (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
are you keeping the application open? hub can't do background sounds, at least it wasn't working a few years ago that route

**Comment by DarthDraconis91** [comment]
yes, originally was using the website of it - kept open in a different tab with no sound notifications then i later downloaded the application still no sound notifications even with it being open

**Comment by TobiTenno** [comment]
oh, i just meant the website by application (cause it's a web app, website application)

**Comment by DarthDraconis91** [comment]
i get ya, but yea i have all three sound filters on i have the cetus night start notification selected for eidolon hunting along with two other notifications selected and not once have i heard the sound filters go off for any of the notifications.

**Comment by DarthDraconis91** [comment]
would also be nice if there was an option on the site to test the sound filter but there isn't

**Comment by TobiTenno** [comment]
@DarthDraconis91 once it deploys, feel free to test #1148's fix.
