### ISSUE TITLE
:bug: Fissure svg icon paths have change on the cdn

### ISSUE THREAD

**Issue by cory-evans** [WFCD/warframe-hub#1178]
### Summary

[source](https://github.com/WFCD/warframe-hub/blob/de4d06b403147789a80ab0168e8f00f4e9f4fc74/components/panels/FissuresPanel.vue#L74C1-L78C43)

SVG icons are no longer named by the tier number.

See: https://github.com/WFCD/genesis-assets/tree/master/svg/fissures

### Version

hub (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
fixing

**Comment by TobiTenno** [comment]
fixed w/ https://github.com/WFCD/genesis-assets/commit/ef78f6bcaab5bf0c6fd76abd871b1f0e0479be65
