### ISSUE TITLE
:bug: Auto progress does not stop

### ISSUE THREAD

**Issue by morionoirom** [WFCD/warframe-hub#1180]
### Summary

"https://hub.warframestat.us/#/" On the website

Turning off the [Auto Progress] switch on the [News] tile does not stop the auto progress.
I want to stop the auto progress because the tile composition changes depending on the presence or absence of the banner image.
If the problem is specific to my environment, please ignore it.

I am not good at English so I cannot explain further.
(Translated by DeepL)

### Version

hub (Default)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
oh, interesting. i'll take a look.

**Comment by TobiTenno** [comment]
@morionoirom sorry it took so long, but the fix is deploying, let us know if you're not seeing it be fixed
