### ISSUE TITLE
:bug: cdn.warframestat.us is 502

### ISSUE THREAD

**Issue by LWF666** [WFCD/warframe-hub#1233]
### Summary

When I open https://hub.warframestat.us/, I found some picture on the page can't load. look like this picture:
![image](https://github.com/WFCD/warframe-hub/assets/44828065/63dbeb89-b892-401c-95dd-cff3ca251a76)

I found through the developer tool of the browser that the link to the image cannot be loaded correctly. When I open the URL of the image separately, it prompts "Bad gateway Error code 502"

look like this picture:
![image](https://github.com/WFCD/warframe-hub/assets/44828065/37950d7f-d57f-4e53-9fd8-fbb765db1208)

### Version

hub (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
yup, it was down for a little while. it's ck up.
