### ISSUE TITLE
Infested invasions' progress bars start at 50%

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#125]
### Infested invasions' progress bars start at 50%
---

**Summary (short):**
Infested Outbreaks' progress bars should start at full green, then gradually become more red/blue.

---
**Description:**
The `attackPercent` and `defendPercent` calculations are correct for Grineer vs. Corpus, but not for Infested Outbreaks.

---
**If issue, Reproduction:**
Wait for a new Infested invasion to pop up, and observe.

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
mmmm, they are supposed to start at 50%, it's intended

**Comment by dsinn** [comment]
Why? The in-game UI always has them at 100% green to start.

**Comment by TobiTenno** [comment]
they were set to start at 50% from when they didn't, because it wasn't always that way.

**Comment by dsinn** [comment]
Then would it be acceptable to update Hub such that it matches how the game has it now?  I don't remember Infested invasions starting at 50% since 2015.

**Comment by TobiTenno** [comment]
it's probably something that'd need to be changed on the api side
