### ISSUE TITLE
Add running time to invasions

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#126]
### Add running time to invasions
---

**Summary (short):**
Requesting that each invasion has its associated running time displayed next to it.

---
**Description:**
The design is pretty much up in the air:
1. What text to display? For example, Deathsnacks uses %.2f for the value, and the unit is "m" for minutes, "h" for hours or "d" for days depending on how much time has passed.
2. Where to place the text?

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
we use badges, could do a popover on the pill on click
