### ISSUE TITLE
List bounties in Ostron bounty cycle

### ISSUE THREAD

**Issue by EricSihaoLin** [WFCD/warframe-hub#13]

**Comment by MainlandHero** [comment]
This feature has been delayed because world state currently does not have the correct translations for each job

**Comment by aliasfalse** [comment]
It has backups automatically generated from their internationalized strings that give the general idea, @MainlandHero. It's safe to use them, because they still get the point across and display the standing, just not the in-game one, and there'd be no new field for it once it's translated upstream (in the worldstate).

**Comment by MainlandHero** [comment]
@aliasfalse What's the percentage of translated strings? I was hoping for about 60% to 70% before I jump on this issue.

**Comment by aliasfalse** [comment]
Of the whole game, or bounties? We have no real estimate of how many bounties there are, so we just add them as we find them.

Right now, it's from one full cycle, and I never really got any more, because I've not been around a computer with the game open much since they launched.

**Comment by MainlandHero** [comment]
@aliasfalse Nah, just the bounties. There's several different categories, and for the sake of calculation, I will assume there's 6 in each category.

Attrition - 6
CaptureBounty - 6
Assassinate - 6
Reclamation - 6

Let's estimate 24? I will update this as I find more

**Comment by aliasfalse** [comment]
:-/ you didn't do the whole string

**Comment by aliasfalse** [comment]
nothing should be holding it back now

**Comment by lostguru** [comment]
Any progress on this? Or has this been delayed?

**Comment by TobiTenno** [comment]
just waiting for prototypes, i think. mainland and i have been superduper busy of late, soz

**Comment by TobiTenno** [comment]
fixed with #70
