### ISSUE TITLE
Expand/collapse click area

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#133]
### Expand/collapse click area
---

**Summary (short):**
It's currently just the text and arrow, but it should probably include the entire blue background as well.

---
**Description:**
Apply the fix to Ostron Bounties, event rewards lists, and Baro's inventory.

---
**Mockups, screenshots, evidence:**
Click the blue background of "Ostron Bounties" instead of the text or arrow.

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
Probably just need to either move the targets for the click form the chevron to the label.... i dunno, i am conflicted on those

**Comment by dsinn** [comment]
The `a[data-toggle]` element currently contains just the text and `.glyphicon`.  Ideally we'd just move up a couple of levels to contain the entire `.panel-heading` and be done.

**Comment by TobiTenno** [comment]
👍
