### ISSUE TITLE
Scrollbar visible on fissures

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#138]
### Scrollbar visible on fissures
---

**Summary (short):**
Scrollbar visible on fissures when using certain display modes with small viewports.

---
**Description:**
Happens on my 1080p monitors on different machines, but not on my Mac's 13" built-in display.

---
**If issue, Reproduction:**
Reduce viewport size until they appear.

---
**Mockups, screenshots, evidence:**
![capture](https://user-images.githubusercontent.com/5075438/42128141-9ade0f08-7c72-11e8-836a-4992c72dc573.PNG)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
Browser?

**Comment by dsinn** [comment]
Firefox, Chrome, Edge, and probably others that aren't installed on this machine. I think it's dependent on display mode, not browser.

**Comment by TobiTenno** [comment]
that still doesn't tell me much, because i can't reproduce it as-is
