### ISSUE TITLE
Fissures added since page load are not sorted

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#140]
### Fissures added since page load are not sorted
---

**Summary (short):**
On page load, fissures are sorted by era in ascending order. However, new fissures are appended to the bottom of the section instead of adhering to the order. Refreshing the page is the current workaround.

---
**Description:**
`updateFissure()` has the following sort function:
```javascript
    fissures.sort((a, b) => {
      const tierA = a.tierNum;
      const tierB = b.tierNum;
      if (tierA < tierB) { return -1; }
      if (tierA > tierB) { return 1; }
      return 0;
    });
```
Adhere to this order.  New fissures should go to the bottom of the relevant era.

---
**If issue, Reproduction:**
Wait until a new non-Axi fissure appears while there is an ongoing Axi fissure.

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
yeah, there's not really a good way to unless we unload and reload all of them whenever one is appended

**Comment by dsinn** [comment]
Currently we just insert it before `#fissureBody` (not to be confused with `.fissure-body`).  I was thinking of going backwards through the `.fissure` elements and calling `.after()` on the first one with equal or lower tier (and default to the beginning of the list).

Given that a new fissure only pops up just a few times an hour and there are usually only 5–9 fissures, I don't believe this approach would be very expensive, and at least I would prefer it over recreating all of those fissure rows.

**Comment by TobiTenno** [comment]
I've got no issue with it if you wanna give it a shot
