### ISSUE TITLE
Ended invasions not cleaned up

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#142]
### Ended invasions should be removed from UI
---

**Summary (short):**
Invasions that have ended should always be removed from the interface.

---
**Description:**
The API returns a limited number of invasions.  If the tab goes to sleep (especially common on mobile devices) and the invasions become so old that their IDs don't show up in the API on the next update, they don't get cleaned up.

---
**If issue, Reproduction:**
Open a tab, switch to another tab for an extended period of time, and return when the API no longer has any trace of the original invasions.

---
**Mockups, screenshots, evidence:**
A new tab shows four invasions, but the old one I left up shows:

![screenshot 2018-07-06 10 57 34](https://user-images.githubusercontent.com/5075438/42386691-31f36c2c-810e-11e8-9f5b-57e33070ef66.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
hmm, that is odd. i've never actually seen this happen, i'll see if i can get it to today.

**Comment by TobiTenno** [comment]
@dsinn if you notice, many of them are on the same planet. the worldstate window groups them by planet
