### ISSUE TITLE
Check for the need to update more frequently

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#150]
### Check for the need to update more frequently
---

**Summary (short):**
Upon waking up a device, the amount of time you need to wait before the worldstate updates should be reduced.

---
**Description:**
`update` currently has a `setTimeout` value of 30 seconds, but we could check for a timestamp every few seconds instead of only relying on that timeout.

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
What timestamp are you checking for? The base worldstate timestamp?

If so, the route is `https://api.warframestat.us/:platform/timestamp`

**Comment by dsinn** [comment]
Thanks. I'll probably be setting an internal timestamp of when the last worldstate update was attempted. That way, I won't bombard the API with requests if the connection is slow or the API is down.
