### ISSUE TITLE
Fish page UI design improvements

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#153]
### Fish page UI improvements
---

**Summary (short):**
There are a number of design issues with the current UI.

---
**Description:**
* Use a striped table instead of the current colours, which don't have an obvious colour mapping and may cause confusion.
  * Colour coding specifically for the enums in the cell contents (e.g., day/night, lake/sea/pond) would help if they match the map legend.
* Replace the image placeholder icons with the real item icons, because the hover action is not available when you're on a phone or when the active window is Warframe.
  * "Hotspots" is the exception because it is not an item. It should have a link to a page that describes it (for mobile users) and hyperlink colour, on top of the existing gif on hover.
* The map's text contrast is bad, the legend is solid black despite being colour indicators, the colours are not colourblind-friendly, and it should be coordinated with the table if possible.
* The Thousand-Year Fish are labelled on the map but have no entry in the legend.
* Fix the expand/collapse area, as was done in #133.

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**
https://hub.warframestat.us/fish

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
The placeholder is there because it keeps it organized. Without it, the table would get overly cluttered.

**Comment by TobiTenno** [comment]
The table colors are based on your theme

**Comment by dsinn** [comment]
Appropriately sized icons would make it look like the foundry and shouldn't add any clutter.

If I end up working on this, I'll remember to go over the row colours for each theme.

**Comment by TobiTenno** [comment]
It's a data table, not the foundry...

**Comment by TobiTenno** [comment]
On the map, if you're referring to the static png, that's totally separate from our styling and rendering, it was given by a community member. There's a dynamic map on https://hub.warframestat.us/map

**Comment by dsinn** [comment]
The foundry embeds a list of items on each row, and so does the fish table.  The placeholders are already occupying the same amount of the space that real item icons would, so my suggestion would only add value to the space that is in use.

Yes, I'm referring to the static map png. I'm open to replacing it with the dynamic map too, but for fishing purposes we would probably want to make some adjustments, like hide the irrelevant stuff and colour-code the enum data.
