### ISSUE TITLE
Long sortie boss name cuts off time badge on mobile

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#155]
### Long sortie boss name cuts off time badge
---

**Summary (short):**
When the sortie boss name is long, the time badge is pushed down and clipped.

---
**Description:**
"General Sargas Ruk" is an example of a sortie boss that causes this.

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**
![screenshot_2018-08-05-17-19-31](https://user-images.githubusercontent.com/5075438/43690216-5c0fe6ce-98d4-11e8-847a-3ad137214b63.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
sorry for the slow time responding. it's because the timer info was put last in the DOM, moving it up fixes it.  fixing it with #167
