### ISSUE TITLE
Wrong description Baal (Europa)

### ISSUE THREAD

**Issue by thorvak** [WFCD/warframe-hub#160]
### Warframe Hub Issue
---

**Summary (short):**

---
**Description:**
It's write Baal (Europa) | Mobile Defense | Neo but it's a Exterminate

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**
https://i.imgur.com/25RuJFN.jpg

---

(Check one)
- [ ] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
This issue was moved to WFCD/warframe-worldstate-data#38

**Comment by TobiTenno** [comment]
@thorvak it's been fixed over on wfcd/warframe-worldstate-data#38
