### ISSUE TITLE
Cache static pages in service worker

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#165]
### Cache static pages in service worker
---

**Summary (short):**
For the sake of offline users who care about those pages, caching them would be nice.

---
**Description:**
- Convert PNG's to JPG's where appropriate (usually large in-game screenshots).
- Update `public/service_worker.js` to include the assets required for the plains and fishing pages to run nicely in offline mode.

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
Closing, #164 is complete.
