### ISSUE TITLE
missionType wrong!

### ISSUE THREAD

**Issue by cagatayldzz** [WFCD/warframe-hub#170]
* Baal (Europa) - Mobile Defence ❌
* Baal (Europa) - Exterminate ✔️

Site screenshots:
![2](https://user-images.githubusercontent.com/7725575/44583776-6d51e880-a7af-11e8-860e-f00df52fb2d3.PNG)

Game screenshots:
![1](https://user-images.githubusercontent.com/7725575/44583779-6fb44280-a7af-11e8-8d72-239ca4ad30a8.PNG)

**Comment by dsinn** [comment]
I see that the node was updated [here](https://github.com/WFCD/warframe-worldstate-data/commit/1b0b51e1cf8ead1853af4957b60867a142108e2f); @TobiTenno, has it not been deployed to production yet?

**Comment by TobiTenno** [comment]
something's up with the api that it's not picking up all the new data from the parser, i'm still re-tweaking the release process on the parser

**Comment by TobiTenno** [comment]
should be fixed now. i'll leave it until @cagatayldzz can confirm.

**Comment by dsinn** [comment]
I'm not sure they'll be watching it that closely, so I'll just close this myself once I see a Baal fissure appear with the correct mission type.

**Comment by TobiTenno** [comment]
👍 thx

**Comment by dsinn** [comment]
![image](https://user-images.githubusercontent.com/5075438/44615402-93a37280-a807-11e8-8694-a1ff9b84ae71.png)

Thanks guys.
