### ISSUE TITLE
Not showing information on Android chrome.

### ISSUE THREAD

**Issue by gbravery** [WFCD/warframe-hub#176]
### Warframe Hub Issue
---

**Summary (short):**
Web page no longer showing any information on my Android device.

---
**Description:**
Just sits with the square rotating in all the components.

---
**If issue, Reproduction:**
Simply go to:
https://hub.warframestat.us
Doesn't seem to matter what platform or theme i choose, nothing seems to be showing any data.
Desktop is fine - just on my android phone.

---
**Mockups, screenshots, evidence:**
![screenshot_20180906-145344](https://user-images.githubusercontent.com/28046548/45161969-df312580-b1e4-11e8-968a-b6b900337aa3.png)

---

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
it takes a minute to load for me but works still.

**Comment by gbravery** [comment]
Left mine for 5m now - still nothing.
OK, I have purged the stored data for this site - and now it works again.

Not sure what the issue with the stored data is (or what the stored data was) but clearing it seems to have solved it.

**Comment by TobiTenno** [comment]
yeah, i'm guessing it was just loading it badly. sorry for the mess!
