### ISSUE TITLE
Reset Timer doesn't respect component settings.

### ISSUE THREAD

**Issue by kylewill0725** [WFCD/warframe-hub#214]
### Warframe Hub Issue
---

**Summary (short):**
Toggling the Reset Timer component setting does nothing.

---
**If issue, Reproduction:**
Open Settings -> Components and toggle the Reset Timer box. Normally you should see the interface update in the background but the Reset Timer doesn't.

---
**Mockups, screenshots, evidence:**
![image](https://user-images.githubusercontent.com/18157392/48805928-623f2380-ecde-11e8-9122-8bddb151946d.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
cool, thanks, i'll go merge that
