### ISSUE TITLE
App doesn't load when localStorage is empty

### ISSUE THREAD

**Issue by dsinn** [WFCD/warframe-hub#223]
### App doesn't load when localStorage is empty
---

**Summary (short):**
If the localStorage is empty, hitting the page shows "Loading..." for a few seconds, and then everything but the header and footer disappear.

---
**Description:**
Occurs on Windows and Mac, Chrome and Firefox.

Refreshing the page after all the "Loading..." text disappears would provide a normal experience, except for Firefox in private browsing mode.

---
**If issue, Reproduction:**
Do any of the following:
- Open an incognito window
- Delete localStorage
- Delete all application storage

Then hit the page.

---
**Mockups, screenshots, evidence:**

![](https://cdn.discordapp.com/attachments/372476825596723210/521612923974713344/unknown.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
fixed with #202
