### ISSUE TITLE
Update platform switcher style

### ISSUE THREAD

**Issue by MainlandHero** [WFCD/warframe-hub#24]
### Warframe Hub Issue
---
---

**Summary (short):**
---

Update platform switcher style

**Description:**
---

Platform switcher style currently is not in the best shape or form, edit to fix some of the style issues

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

![screen shot 2017-10-24 at 3 21 02 pm](https://user-images.githubusercontent.com/1594432/31963639-69129b18-b8cf-11e7-9f8f-016842643ddc.png)
![screen shot 2017-10-24 at 3 24 38 pm](https://user-images.githubusercontent.com/1594432/31963665-7b61fa52-b8cf-11e7-958e-235c58a0d0b1.png)

(Check one)
- [ ] Issue
- [X] Suggestion

**Comment by mcoirault** [comment]
Hey @MainlandHero and happy Hacktober fest,

If you're open for contributions, I'll take care of this. 😄

**Comment by MainlandHero** [comment]
@mcoirault Of course, pull requests are welcome. I just hope you don't mind the lint and deploy reviews at the end =P

**Comment by MainlandHero** [comment]
This has been solved by @mcoirault, and has been included in latest PR #38
