### ISSUE TITLE
PS4 Ghoul Purge isn't showing any rewards

### ISSUE THREAD

**Issue by gbravery** [WFCD/warframe-hub#243]
### Warframe Hub Issue
---

**Summary (short):**
Ghoul purge on PS4 isn't showing any rewards

---
**Description:**
As summary  - when you expand rewards, says "Pattern Mismatch. Results inaccurate."

---
**If issue, Reproduction:**
Open https://hub.warframestat.us/timer#
Choose PS4 platform
Click on either Rewards expanding section in Ghoul Purge component.

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by gbravery** [comment]
This might be more wide ranging - does the same in the Ostron Bounties Reward column too.


Reclaim the Stolen Artifact | 440, 440, 440 | 5-15 | Pattern Mismatch. Results inaccurate.

**Comment by Mizotizoi** [comment]
Hi, the Ostron Bounties in PC have the same problem "Pattern Mismatch. Results inaccurate."... 
It may be possible to put the **rotation letter** in the tittle before expands the bounties ? There are only 3 rotation (A,B,C), they always have the same rewards and mirror the rotation in Fortuna so it may be helpful to see it.
First time posting here. Thanks for all the work, the Warframe Hub helps a lot.

**Comment by TobiTenno** [comment]
The issue was on our parser, not here, and it's since been fixed. Sorry for the inconvenience.
