### ISSUE TITLE
Cetus night time offset incorrect?

### ISSUE THREAD

**Issue by MainlandHero** [WFCD/warframe-hub#26]
### Warframe Hub Issue
---
---

**Summary (short):**
---

User reported that Cetus night time is incorrect, as Eidolon generally spawns 2 minutes before timer says night.

**Description:**
---

Requesting investigation for a user complaint: User (Loky) reported that Cetus night time is incorrect, as Eidolon generally spawns 2 minutes before timer says night.

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

![screen shot 2017-10-24 at 3 49 41 pm](https://user-images.githubusercontent.com/1594432/31964740-0211045a-b8d3-11e7-9a61-2d919448e893.png)

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by aliasfalse** [comment]
hmmm, that's a fair point. we do offset by, what, 780s or something?

**Comment by aliasfalse** [comment]
Also, where dis

**Comment by MainlandHero** [comment]
@aliasfalse This discussion was in #bug-report text channel

**Comment by MainlandHero** [comment]
![screen shot 2017-10-24 at 4 18 19 pm](https://user-images.githubusercontent.com/1594432/31965967-13249d0c-b8d7-11e7-92d4-e530ce3e6024.png)

**Comment by MainlandHero** [comment]
@aliasfalse Consider offset for -2 minutes?

**Comment by aliasfalse** [comment]
yeah, i'll push it to the parser in a sec.
