### ISSUE TITLE
The Amount of Logs is Too Damn High

### ISSUE THREAD

**Issue by aliasfalse** [WFCD/warframe-hub#28]
### Warframe Hub Issue
---
---

**Summary (short):**
![1y6u0f](https://user-images.githubusercontent.com/7128721/31968731-b055f29c-b8d7-11e7-98ea-36a4af60db9c.jpg)

---
**Description:** N/A

---
**If issue, Reproduction:** Look at the logs!!!

---
**Mockups, screenshots, evidence:** 

![hub-spam-log-small](https://user-images.githubusercontent.com/7128721/31968795-f4714ba2-b8d7-11e7-8706-91aefb107f51.gif)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by MainlandHero** [comment]
This has been solved in PR #38
