### ISSUE TITLE
daily reward timer is in -minus.. also the old news was better 

### ISSUE THREAD

**Issue by Psyqoo** [WFCD/warframe-hub#291]
### Warframe Hub Issue
---

**Summary (short):**
first time for me here 
reward login timer is bugged and the new news component is not helpful like before 

---
**Description:**
1st issue is here https://i.imgur.com/xhoJiwd.png 

2nd .. the old news component was simple and clear .. just look at it for 1 sec and you find what you want if there is a new update or new dev stream ..etc ... now i have to move my mouse to the arrows and click it multiple times to see if there is anything new 
i always play the game while wf-hub is open in chrome ..and all i need is alt-tab to see alerts, invasions, sorti conditions, etc and i dnd need to use my mouse .. just alt+tab and back to the game 
i hope old news component  returns back .. plz 

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by dsinn** [comment]
Thanks for opening an issue, but this is actually one issue and one suggestion.  Could you make a separate issue for the news suggestion and edit this one to only contain the daily reset bug?
