### ISSUE TITLE
Include a link to old-hub

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#294]
### Warframe Hub Issue
---

**Summary (short):** Provide a link to [old-hub](https://old-hub.warframestat.us)

---
**Description:**
Open to discussion where, but might help for people moving over to see the difference, or if something is breaking, to have the old "stable", for as long as it still works.

---
**If issue, Reproduction:** :x:

---
**Mockups, screenshots, evidence:** :x:

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
@dsinn what would you think of putting it into the tools dropdown?

**Comment by dsinn** [comment]
@TobiTenno Where is that exactly?

**Comment by TobiTenno** [comment]
[here](https://github.com/WFCD/warframe-hub/blob/dev/src/components/Navbar.vue#L20)

**Comment by dsinn** [comment]
So, like, appending another `<b-nav-item>` to the end of the `<b-navbar-nav>`?  I'd be okay with that.

**Comment by dsinn** [comment]
I'd be okay with putting it under the Projects dropdown.
