### ISSUE TITLE
Fish Table Items should link to wiki

### ISSUE THREAD

**Issue by MainlandHero** [WFCD/warframe-hub#30]
### Warframe Hub Issue
---
---

**Summary (short):**
---

Fish Table Items should link to wiki

**Description:**
---

ScruffyRules' suggestion: Fish Table Items should link to wiki

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

(Check one)
- [ ] Issue
- [X] Suggestion

**Comment by MainlandHero** [comment]
It seems like Warframe Wiki does not have dedicated articles for fish type and baits, but unique meat can be a possibility!

**Comment by aliasfalse** [comment]
Completed with #31
