### ISSUE TITLE
Components are Visually broken in new Design

### ISSUE THREAD

**Issue by fuba82** [WFCD/warframe-hub#303]
Summary (short):
---
1. Components go **anywhere** after move them
2. Ostron Bounty Cycle and Solaris United Bounty Cycle Dropdown's overlap other Components or get overlaped by another Components

Description:
---
Video here:
https://youtu.be/fDUfK2-3I1s

Reproduction:
---
Look Video

Screenshots, evidence:
---
Look Video

**Comment by TobiTenno** [comment]
dupe of #288  and #287
