### ISSUE TITLE
Add construction progress panel

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#308]
Summary (short):
---
Give an active panel showing the construction progress for a platform

Description:
---
Get data from `constructionProgress`

Mockups:
---
maybe later

**Comment by Bitti09** [comment]
Idea of how the component  can look like:

![image](https://user-images.githubusercontent.com/187045/59162161-9ba97600-8aec-11e9-9837-3c3a2e60f6bf.png)
