### ISSUE TITLE
Rename `state` on components to `display`

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#318]
Summary (short):
---
The name `state` for whether or not to display the component is ambiguous, it'd be better to rename it.

Description:
---
Discussed in #309, the name `state` for displaying or not displaying a component is a bit confusing.

Reproduction:
---
_1. I did this_
_2. Then i did this_
_3. And I expected X but got Y._

Screenshots, evidence:
---
:x:

**Comment by 107g** [comment]
I might have a closer look on that issue in the not-so-distant future.

**Comment by 107g** [comment]
There is already an attribute called 'display' for each component local state:
```js
"invasions": {
    "state": true,
    "display": "Invasions",
    "key": "invasions",
    "component": "InvasionsPanel",
    "expand":false,
    "props": {
      "invasions": "@worldstate.invasions"
    }
```

I'm trying to figure out what purpose it has.

EDIT: I found it, it is used in the settings component.
