### ISSUE TITLE
all times are in negative 

### ISSUE THREAD

**Issue by Psyqoo** [WFCD/warframe-hub#325]
Summary (short):
both old and new hub pages the timers are in negative also fissure missions are not shown in old hub page
_short description of what's wrong_

Description:
---
Longer, more technical description if possible

Reproduction:
---
_1. I did this_
_2. Then i did this_
_3. And I expected X but got Y._

Screenshots, evidence:
new hub page : https://i.imgur.com/2bHUGc7.png
old hub page: https://i.imgur.com/hV7Qii6.png
Screenshot so it's easy for us to compare

**Comment by SlayerOrnstein** [comment]
It might be and issue with the worldstate parser or status, because Navis is getting the same issues with fissures and both Cetus and Vallis cycles.

Edit: bounty timer as well

**Comment by EricSihaoLin** [comment]
I can verify the issue, let me see if I can track down where the issue is coming from.

Edit: @TobiTenno This is confirmed a worldstate issue on warframestat.us

**Comment by dsinn** [comment]
At least on the Hub pages, the problem seems to have resolved itself for me. Don't know how easy it is to track down the cause.

**Comment by EricSihaoLin** [comment]
@dsinn Seems like either @TobiTenno was working on fixing it, or the worldstate parser has recovered itself. The worldstate was all in negative about a few hours back: https://ws.warframestat.us/pc

Currently, only cycle information is down, but should be back up starting the next cycle as Genesis has resumed reporting cycles.

**Comment by TobiTenno** [comment]
It was an error on the machine it was running on due to space running out. It should be remedied at present.
