### ISSUE TITLE
Dropdatabase outdated

### ISSUE THREAD

**Issue by m0ltay** [WFCD/warframe-hub#329]
Summary (short):
---
Drop Database last parsed on June 24th

![image](https://user-images.githubusercontent.com/52664130/60813791-b7a84200-a194-11e9-87ce-4742cdb585db.png)

**Comment by EricSihaoLin** [comment]
Hi, this is the wrong project. Drops is a separate project by other developers: https://github.com/WFCD/warframe-drop-data
