### ISSUE TITLE
localized strings are russian instead of english

### ISSUE THREAD

**Issue by nonchip** [WFCD/warframe-hub#339]
Summary (short):
---

planet and item names are in Russian, even though my system language is english.

Description:
---

my browser sends `accept-language: en-US,en;q=0.9,de;q=0.8`, but the website contains location names like "Selkie (Седна)" and sortie descriptions like "Элементальное улучшение врага: Электричество".

this does *not* apply to the whole website, just (some?) strings localized through the warframe api, so my guess is you're looking up the wrong strings in `languages.json`

Reproduction:
---

1. open https://hub.warframestat.us/ with an english locale setting
2. get russian localized strings

Screenshots, evidence:
---
![s](https://user-images.githubusercontent.com/601018/62004266-1d984180-b123-11e9-8974-4a0f36620687.png)

**Comment by nonchip** [comment]
also, those labels are wrong and i didn't select them (and i'm forbidden from changing them), the only thing i got to choose was "Type: Bug".

**Comment by nonchip** [comment]
aaaaand it just got fixed without me even reloading (so it was something delivered via the ajax api). dunno if anyone actually did something about this or if it randomly broke&unbroke, so i'll leave this open for now so you know about it.

**Comment by ElGenerico** [comment]
I've also been getting both Russian and Chinese frequently for the past few days, which eventually changes to English.

**Comment by nonchip** [comment]
yup still not fixed, yesterday it was german for about half an hour.

you're not caching the `languages.json` results, are you? ;P

also someone *please* fix those bullshit tags github automatically assigned, as a "docs, inconvenient" issue nobody's gonna take note of the "not just docs, and makes the site unusable for everyone but language nerds" problem! (@TobiTenno since you're pretty active in the issues lately, i'm bringing this to your attention)

**Comment by TobiTenno** [comment]
not a hub error, this is from the api.

**Comment by nonchip** [comment]
@TobiTenno if by that you mean the official (=DE hosted) worldstate api, then i'm afraid that's unlikely, because the game, Cephalon Genesis and my own api client (which was talking to content.warframe.com with some help from api.warframestat.us to resolve the `/Lotus/...` "unique names") were telling me the same things in english while that happened. if you mean a warframestat.us api, could you please tell me which one so i can report it accordingly?

**Comment by TobiTenno** [comment]
No, I don't. 

I mean that it's an error on the API that Genesis, hub, and many other projects share usage of. 

I am aware of it already, and for API-specific issues, you can log them to wfcd/warframe-status
