### ISSUE TITLE
Site language cycles

### ISSUE THREAD

**Issue by 00packman00** [WFCD/warframe-hub#344]
Summary (short):
---
website language seems to cycles 

Description:
cycles between english, russian, chinese, spanish and more. Seems to coincide with invasion progress bar color changes.

Reproduction:
---
_1. Happens when sitting on website for a while
_2. Refresh (F5) will reset back to English occasionally

Screenshots, evidence:
---
Screenshot so it's easy for us to compare
![2019-08-19_18-09-32](https://user-images.githubusercontent.com/54295264/63316999-04b82180-c2c6-11e9-9817-cc1e0fd9d9ed.png)

**Comment by TobiTenno** [comment]
the language comes from the api, hub itself doesn't control this. it's related to the issue I referenced above.
I'll leave this open, but blocked, because it's not really something that can be fixed from the hub side.

**Comment by TobiTenno** [comment]
The upstream issue (wfcd/warframe-status#91) was fixed a couple weeks ago, so i'm closing this.
