### ISSUE TITLE
Accessibility Changes

### ISSUE THREAD

**Issue by aliasfalse** [WFCD/warframe-hub#35]
### Warframe Hub Issue
---
---

**Summary (short):** Accessibility Fixes

---
**Description:** 
- [ ] Add button names
- [ ] Add Link Names
- [ ] Lang attribute for html elements

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**
![image](https://user-images.githubusercontent.com/7128721/32007743-0783a800-b970-11e7-891a-28cfb392d23d.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by MainlandHero** [comment]
This has supposedly been resolved by PR #37
