### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by aliasfalse** [WFCD/warframe-hub#36]
### Warframe Hub Issue
---
---

**Summary (short):** Fulfill Chrome's best practices

---
**Description:** 
- [ ] Use `rel="noopener` for links
- [ ] Shorten "app name"

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**
![image](https://user-images.githubusercontent.com/7128721/32007835-46b56bda-b970-11e7-841d-8b719c03380f.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by MainlandHero** [comment]
This has been solved with PR #37

**Comment by aliasfalse** [comment]
@MainlandHero did the app name get cleared up?
