### ISSUE TITLE
Night Compact Theme - missing 'day/night/warm/cold' qualifier on Earth, Cetus, Vallis timers

### ISSUE THREAD

**Issue by venzy** [WFCD/warframe-hub#370]
Summary (short):
---
Using 'Night Compact' theme - the Earth and Cetus cycle timers at the top of page show the countdowns but not the day/night info for Earth/Cetus, and Warm/Cold for Vallis.  This was there a few days ago (~2019-11-14).
They are present for other themes.

Description:
---
Using both Chrome 78 (normal profile and incognito) and Microsoft Edge 44.
It looks like the info's still there in Chrome DevTools, it's just not getting rendered by CSS or something.

Reproduction:
---
1. Open hub.warframestat.us
2. Use the Settings icon at top right, select Theme, select Night Compact, click OK
3. Site changes to use Night Compact theme, but the mentioned info is missing from the top of page cycle timers.

Screenshots, evidence:
---
![Missing Cycle Timer Qualifier 2019-11-17](https://user-images.githubusercontent.com/1972305/69002997-3df44200-0946-11ea-988c-bfeee5f524a9.png)
![Devtools Elements 2019-11-17](https://user-images.githubusercontent.com/1972305/69003002-48164080-0946-11ea-8dd7-72796485894b.png)

**Comment by EricSihaoLin** [comment]
Can't seem to reproduce...
![image](https://user-images.githubusercontent.com/1594432/69003382-f8e0f900-08ce-11ea-9476-8b5ceed357ad.png)
![image](https://user-images.githubusercontent.com/1594432/69003394-4cebdd80-08cf-11ea-8f04-9f2fb6280e52.png)

**Comment by EricSihaoLin** [comment]
I see that you might be using a slimmer version, but I also tried that, and all the timers are showing for me?
![image](https://user-images.githubusercontent.com/1594432/69003389-2a59c480-08cf-11ea-85c2-bb9676d2f185.png)

**Comment by venzy** [comment]
@EricSihaoLin - your screenshots show the same problem as mine.  There is no word or icon for 'day' or 'night' next to each timer (or 'cold' or 'warm' for Vallis).

**Comment by EricSihaoLin** [comment]
@venzy Oh I see, sorry!
It's late and my brain was probably off. I should be able to push out a fix tomorrow!

**Comment by EricSihaoLin** [comment]
@venzy Should be fixed in #372 and is live on hub. Please make sure to hard refresh and see the new css changes.
