### ISSUE TITLE
Safari shows Vue.js icon in Safari

### ISSUE THREAD

**Issue by alexkoala** [WFCD/warframe-hub#380]
Summary (short):
---
Safari shows Vue.js icon in Safari tab.

Description:
---
Rendered site source:
`<link rel="mask-icon" href="/img/icons/safari-pinned-tab.svg" color="#1a5072">`

The icon path is `/public/img/icons/safari-pinned-tab.svg` in `dev` branch.

Reproduction:
---
_1. Open Warframe Hub on macOS Safari._
_2. Pin tab or turn on `show website icon` settings._
_3. It shows Vue.js icon._

Screenshots, evidence:
---

<img width="401" alt="2019-12-12_12 15 49" src="https://user-images.githubusercontent.com/44674417/70797084-18dcdd00-1de7-11ea-8bdf-0be8a1173bfa.png">

**Comment by TobiTenno** [comment]
sorry for not much progress, i'm still not sure why it's using the wrong icon, cause the icon in our repo is definitely one of our icons

**Comment by alexkoala** [comment]
Fixed in #382

**Comment by TobiTenno** [comment]
🤦‍♂ totally didn't see that
