### ISSUE TITLE
[minor] given only TLS1.2 is supported, whats the point of building for IE9 and IE10 ?

### ISSUE THREAD

**Issue by birdspider** [WFCD/warframe-hub#389]
Summary
---
Align `.browserlistrc` supported browser with network-stack supported browsers

Description:
---

[.browserlistrc](https://github.com/WFCD/warframe-hub/blob/dev/.browserlistrc#L5)
```
# Browsers we support

\> 1%
last 2 versions
not ie <= 8
```

versus

```
$ nmap --script ssl-enum-ciphers -p 443 hub.warframestat.us
Starting Nmap 7.80 ( https://nmap.org ) at 2020-01-16 18:12 CET
Nmap scan report for hub.warframestat.us (104.28.20.115)
Host is up (0.026s latency).
Other addresses for hub.warframestat.us (not scanned): 104.28.21.115

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256-draft (ecdh_x25519) - A
|     compressors:
|       NULL
|     cipher preference: client
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 1.48 seconds
```

and [caniuse TLS 1.2](https://caniuse.com/#feat=tls1-2)

**TLS1.2 is only supported by default IE11 upwards**

--- 

I'd recommend something like

```
# Browsers we support

\> 1%             // [or]
last 2 versions   // [or] already encompasses IE11,10
Firefox ESR       // [or]
not dead          // removes IE 10
```
which is basicly browserslist [`defaults`](https://github.com/browserslist/browserslist#queries) anyway, [demo](https://browserl.ist/?q=%3E+1%25%2C+last+2+versions%2C+Firefox+ESR%2C+not+dead)

**Comment by TobiTenno** [comment]
> ie 9 & 10

these are default values for the vue browserlist, we've not specific preferences on it

**Comment by birdspider** [comment]
Ah @TobiTenno you mean this was created during `vue create <app>` or whatever that command is ?

well it creates a following entry today (in package.json):

``` 
"browserslist": [
  "> 1%",
  "last 2 versions"
]
```

in any case it should match the actual browsers you want to support, otherwise your js-bundle gets larger with polyfills for i.e. IE10 which can't open the website anyway.

**Comment by TobiTenno** [comment]
i separated it out at some point without changes at some point due to other issues.

**Comment by TobiTenno** [comment]
if you'd like to submit a pr to change it, feel free, and we can discuss it there

**Comment by TobiTenno** [comment]
That's the default entry, now, 2 years after we made this project...
