### ISSUE TITLE
Is there a reason for not using `ga/anonymizeIp:true`  

### ISSUE THREAD

**Issue by birdspider** [WFCD/warframe-hub#390]
Is there any reason for not beeing more private by default ?

[google dev article](https://developers.google.com/analytics/devguides/collection/analyticsjs/ip-anonymization), for `vue-analytics` I think it would be:
```
Vue.use(VueAnalytics, {
  id: 'UA-XXX-X',
  set: [
    { field: 'anonymizeIp', value: true }
  ]
})
```

**Comment by TobiTenno** [comment]
yes, cause it's not the default. assuming devs are gonna use a non-default from a random analytics article they've never heard of is probably a stretch

**Comment by TobiTenno** [comment]
if you'd like to submit a pr with a request to anonymize it, I'll probably take it, but the tone of your issue needs a second look.

**Comment by birdspider** [comment]
@ToniTenno I'm sorry if my tone gave a negative impression, I would like to do a PR, thats exactly why I'm asking if there is a underlying reason for it not being set to `true`. 

The _random analytics article_ I linked is the _official google documentation_ btw. 

---

regarding potential other PRs, should I do/start them, then ask if they are wanted? or should I ask if they are wanted and then PR them ?

**Comment by TobiTenno** [comment]
the random analytics article is on an official google documentation that isn't linked to the module and is under a miscellaneous guides section that we have no reason to go to unless we're looking for it.

Yes, feel free to submit a PR and we can discuss their necessity on the PR
