### ISSUE TITLE
Acolyte tracker no longer works

### ISSUE THREAD

**Issue by kgptzac** [WFCD/warframe-hub#401]
Earlier today the acolyte tracker was working, but later it's no longer shown.  What takes?

**Comment by TobiTenno** [comment]
do a hard refresh, we fixed it yesterday. there was an issue with the string translator.

**Comment by kgptzac** [comment]
I saw acolyte status last night after I raised this issue... and today right now it's gone again.

**Comment by TobiTenno** [comment]
did you try doing a hard refresh?  (CTRL+SHIFT+R on chrome-based browsers)
