### ISSUE TITLE
Interested in contributing to the project

### ISSUE THREAD

**Issue by ShadabFaiz** [WFCD/warframe-hub#404]
Hi everyone.
First of all, let me tell you that you guys have made a great website. It is so helpful in getting the required information about the events, missions, day/night cycle, etc. It is really wonderful.
Having said that, I'm interested in contributing to the project. I have looked into the contributing guidelines, it does not clarify a few things.
1. On what issue/feature can I work on?
2. Can I select an issue on my own and start working on it? (currently, I can see there are some UI issues under setting models. They are not mobile responsive and also some of the elements are taking unnecessary space.)
3. While working on an issue, if I find another issue, then do I need to create a sperate pull request for that?

**Comment by TobiTenno** [comment]
Welcome!
1. Whatever you like, we just review things a good bit to make sure things stay consistent.
2. For sure! feel free to work on whatever catches your eye
3. We prefer separate ~~issues~~ pr's primarily so it's easy to see the changes discretely and make suggestions that are targeted to one thing without the possibility of missing something else while you're making something.

**Comment by ShadabFaiz** [comment]
Nice. Thank for the information.
