### ISSUE TITLE
Png images replacement with webp format?

### ISSUE THREAD

**Issue by ShadabFaiz** [WFCD/warframe-hub#408]
I was going through the assets of the repository and I noticed that we are using large size png images. Is there any specific reason to not serve these images in webp format since images in webp format can be very small compared to their png format. One such example is the file: orbvallis.png
Currently, it's size is 2.9MB. After converting it to webp, its size is reduced to 730KB and quality is also still really good. As for the backward compatibility is considered, we can have a fall back to use png if the browser does not support it.

**Comment by TobiTenno** [comment]
At this point, with the browser restrictions we have in place, I don't know that we have any reason not to move them all that are pngs, just hasn't been done.

**Comment by TobiTenno** [comment]
When we did have to have them for backwards comparability, we pretty much thought it was kind of a waste to bundle the larger png (thus still taking up assets over the wire and in our bundle) but using either... At least that was my thought process. I know for all external images that we pull in, we run them through a caravaggio instance before we load them so we get a regulated dimension/size/format image, and those are all webp

**Comment by TobiTenno** [comment]
If you're down for it, feel free. I look forward to seeing it if you decide to do so.

**Comment by ShadabFaiz** [comment]
Ok. Are we going to add support for backward compatibility also?

**Comment by TobiTenno** [comment]
given the browser restrictions we have in place, i don't know that it's necessary to have the backwards compatability for png, and we can just lock it to webp getting generated.

**Comment by ShadabFaiz** [comment]
Ok
