### ISSUE TITLE
Arbitration Timer Inaccurate 

### ISSUE THREAD

**Issue by auroralovecraft** [WFCD/warframe-hub#417]
The Arbitration tracker recently, within the last day or so, started displaying crazy long timers, like 10 hours long. I've tried a couple of things since the bug occured to 'fix' it on my end, such as refreshing the page, closing it and opening a new one, restarting my browser, even down to restarting my pc, it's still inaccurate. Screenshot provided below, taken a few minutes ago before typing this out. 

Unseen in the image below, is the text on screen "vibrating". It changes sizes constantly, though I believe this may be a graphical glitch on my end, because everytime I've gone to capture evidence with a screen recorder, like obs, once the program opens, the text shifting stops. So that is probably something on my end. 

![Arbitration Timer Inaccurate](https://user-images.githubusercontent.com/63195745/78500390-b30cbc00-771b-11ea-8d5b-7b1952b603ba.png)

Edit: I finally managed to capture evidence of that visual bug I mentioned. Sorry for the bad quality, converting the video into a gif absolutely destroyed it. It's worthy to note that this is the only website that does this "vibrating" thing for me. 
![ezgif-3-92a155317165](https://user-images.githubusercontent.com/63195745/78500666-8194f000-771d-11ea-8e64-8a8ff9aec906.gif)

**Comment by TobiTenno** [comment]
We pull the arbitration time from an upstream source, so there's not much we can do about that.

Also, it's impossible to read it on your gif, but we know it's messed up.

**Comment by TobiTenno** [comment]
closing, as it's being handled in https://github.com/WFCD/warframe-worldstate-parser/issues/196
