### ISSUE TITLE
Disclaimer in about page that anything could be inaccurate

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#429]
Summary (short):
---
Just a short disclaimer in our about section that stuff could be out of date or inaccurate depending on what DE sends us.

**Comment by esunder** [comment]
@TobiTenno I can knock this one out for you. What do you think about this wording:

![image](https://user-images.githubusercontent.com/357754/94883220-b5807200-042f-11eb-88ad-e65a244a0676.png)

**Comment by TobiTenno** [comment]
I would make the because clause either after the information clause, or make because "Due to", just don't start the se fence with because
