### ISSUE TITLE
Website Optimization (Static Content Caching)

### ISSUE THREAD

**Issue by MainlandHero** [WFCD/warframe-hub#44]
### Warframe Hub Issue
---
---

**Summary (short):**
---

The website should enable caching of some sort.

**Description:**
---

Per @ScruffyRules, the website needs to be optimized.
This will be the caching part of static content.

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by MainlandHero** [comment]
This has been solved in latest commit
0518343d5a9fd4e24b41ab267e43df0cd7b80467

**Comment by aliasfalse** [comment]
docs in the commit are for 7 days, the actual time is 1 year

**Comment by ScruffyRules** [comment]
Isn't it 1 day? maxAge is in milliseconds.

**Comment by MainlandHero** [comment]
@ScruffyRules and @aliasfalse, you're absolutely right.
This is why I shouldn't try to code when it's too late at night.
Fixed my intentions in 34fb1d85780e7d7d6dbebd07663763c7ccc91896
