### ISSUE TITLE
Plains of Eidolon timer incorrect

### ISSUE THREAD

**Issue by tokyotapes** [WFCD/warframe-hub#455]
Summary (short):
---
Website is showing its currently Night but in-game it shows it's not for another 30 minutes.  This is at 11:01 PM CST 9/7/2020

Screenshots, evidence:
---

![image](https://user-images.githubusercontent.com/1209807/92432410-ade6e980-f15f-11ea-8c2c-d9f432b62bf5.png)

**Comment by TobiTenno** [comment]
have you checked your device time and date?

**Comment by TobiTenno** [comment]
Also, that's Earth, not Cetus
