### ISSUE TITLE
Poe and Vallis open world swapped

### ISSUE THREAD

**Issue by cyberfuzzie** [WFCD/warframe-hub#466]
Summary (short):
---
The links to Plains Map / Fishing Data / How to Fish show the Vallis pages, and vice versa.

Description:
---
I suspect the changed in bf8f1a5 in router.js to be the issue:
```
import PoEMap from './views/OpenWorld/Venus/Map.vue';
import PoEFish from './views/OpenWorld/Venus/Fish.vue';
import HowToFish from './views/OpenWorld/Venus/HowToFish.vue';

import VallisFish from './views/OpenWorld/Earth/Fish.vue';
import VallisMap from './views/OpenWorld/Earth/Map.vue';
import HowToFishVallis from './views/OpenWorld/Earth/HowToFish.vue';
```

Reproduction:
---
_1. Click in the navigation on Open World -> Plains Map
_2. I expect the PoE map, but got the Orb Vallis map

**Comment by TobiTenno** [comment]
interdasting. i'll fix that.
