### ISSUE TITLE
Void Trader Inventory Issue

### ISSUE THREAD

**Issue by MainlandHero** [WFCD/warframe-hub#47]
### Warframe Hub Issue
---
---

**Summary (short):**
---

When switching platforms, old void trader inventory remains

**Description:**
---

When switching platforms, old void trader inventory remains

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by MainlandHero** [comment]
This should be resolved with latest release.

**Comment by TobiTenno** [comment]
👍
