### ISSUE TITLE
baro's time incorrect

### ISSUE THREAD

**Issue by cptmacp** [WFCD/warframe-hub#472]
baro's time is invalid
seems like its behind 2days 
but hours are correct

https://warframe.fandom.com/wiki/Baro_Ki%27Teer

**Comment by TobiTenno** [comment]
We consume our own API that has worked fine up to now. You wanna see what's wrong on the worldstate itself and report back, cause we don't use a pattern, we use data directly from DE

**Comment by TobiTenno** [comment]
Void trader looks fine.

![image](https://user-images.githubusercontent.com/7128721/103472134-5cd2b500-4d4f-11eb-8b9a-3f7d390c006b.png)
