### ISSUE TITLE
Some timer divs constantly jiggle in Firefox

### ISSUE THREAD

**Issue by NaomiKeller** [WFCD/warframe-hub#485]
Summary (short):
---
Content within the columns column jiggle back and forth. This issue seems to only be present in Firefox.

Description:
---
It's a minor issue, but I use Firefox as my primary browser and it is pretty distracting when I use the site. It seems to only happen in the second and third columns. It seems like the issue is the divs are constantly fluctuating in size, primarily horizontally. I thought it may be tied to the timer updates every second, but it seems to be occurring around twice a second. 

Perhaps its a limitation with Firefox because of however you made the style, or maybe its an issue specific to my browser/extensions. Just wanted to let you know.

Reproduction:
---
-NA-, it just always happens 

Screenshots, evidence:
---
https://user-images.githubusercontent.com/9884119/116833517-95f92580-ab87-11eb-8028-e7613c540444.mp4

**Comment by TobiTenno** [comment]
i'll be honest, I don't really like or (personally) support firefox, cause it does weird stuff like this when it shouldn't >.<

**Comment by TobiTenno** [comment]
closed with #509
