### ISSUE TITLE
https://api.warframestat.us/pc isn't responding to other locations

### ISSUE THREAD

**Issue by 4E71-NOP** [WFCD/warframe-hub#493]
Summary (short):
---
Try in your browser https://api.warframestat.us/pc -> no response it seems.

Description:
---
Trying https://api.warframestat.us/pc, Firefox says "server not found".

If you call it differently the console the error is :
*Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.warframestat.us/pc. (Reason: CORS request did not succeed).*

Reproduction:
---
Try in your browser https://api.warframestat.us/pc

Maybe some rules have changed on the host. Is it intended ?

**Comment by 4E71-NOP** [comment]
Seems to be resolved. Let's keep it for a dey or two.
Thanks to the one who solved it.

**Comment by TobiTenno** [comment]
It was probably a temporary downtime related to the fastly/cloudflare issue.
