### ISSUE TITLE
unable to activate Steel Path component once disabled

### ISSUE THREAD

**Issue by NFlieger** [WFCD/warframe-hub#496]
Summary (short):
---
Once you have deactivated the component "Steel Path" in the settings, you have no chance of turning it back on.

Description:
---
The Steel Path component seems to be linked to other components and not have it's own panel.
If you deactivate any component, the Steel Path component will be deactivated as well. Even before confirming your new components you selected in the settings by using the OK button, the panel will be hidden and components.steelPath.display in your local storage will be set to false.
From now on there is no way to set that value to true again. If you activate it in the settings menu, the panel will not show up and still be hidden, even though it looks activated in the settings menu. Once you close the settings and open it again, it show the correct status of deactivated again.
If you delete your local storage, the panel will show up again, since the initial value seems to be true.

Right now it is only possible to see the Steel Path component, if you make no changes to the components at all.

Reproduction:
---
1. Open the Settings -> Components menu
2. Deactivate any component of your liking
3. The indicator for that component will show it is disabled now (as expected)
4. Steel Path will be indicated as well (not expected)
5. Close the menu (Cancel, OK, X makes no difference)
6. Both panel will be hidden now (not expected)

Screenshots, evidence:
---
https://imgur.com/2LPX14K

**Comment by TobiTenno** [comment]
weird, thought I'd fixed that. I'll get on it tonight.

**Comment by TobiTenno** [comment]
Could you try the PR over on #498 to make sure it works for you, @NFlieger?

**Comment by NFlieger** [comment]
The deployed preview in #498 works. The pull request seems to fix the issue. I am looking forward for it being deployed into production.

**Comment by TobiTenno** [comment]
It should already be deployed. You may need to do a hard refresh (on Chrome-based browsers: Ctrl+Shift+F5) to force it to pull some new content, but the host should handle that (hopefully!)
