### ISSUE TITLE
Missing Fish "Lobotriscid" from Open World tab > Cambion Drift > Fishing Data

### ISSUE THREAD

**Issue by GioGr** [WFCD/warframe-hub#499]
https://warframe.fandom.com/wiki/Lobotriscid#Cambion_Drift

**Comment by TobiTenno** [comment]
ah, thanks for catching it. if you have time, feel free to throw it in the json data, or I'll get it sometime soon.

also, for future usage, please use the bug template, not an empty freeform issue template.

**Comment by GioGr** [comment]
```

  {
    "name": "Lobotriscid",
    "thumb": "lobotriscid",
    "wiki": "https://warframe.fandom.com/wiki/Lobotriscid",
    "unique": [{
      "name": "Parasitic Tethermaw",
      "thumb": "sebum",
      "wiki": "https://warframe.fandom.com/wiki/Parasitic_Tethermaw"
    }],
    "location": "Surface",
    "time": {
      "string": "Any",
      "fass": {
        "appear": false,
        "prefer": false
      },
      "vome": {
        "appear": true,
        "prefer": false
      }
    },
    "rarity": "1-Common",
    "bait": {
      "name": "None",
      "recommended": false
    },
    "spear": {
      "spari": true,
      "ebisu": true
    },
    "maximumMass": "16kg",
    "small": {
      "resources": {
        "tumor": 3,
        "bladder": 3
      }
    },
    "medium": {
      "resources": {
        "tumor": 4,
        "bladder": 4
      }
    },
    "large": {
      "resources": {
        "tumor": 6,
        "bladder": 6
      }
    }
  },
```
for the thumbs(unique and fish) idk wt to enter 📦

**Comment by TobiTenno** [comment]
if you put links to their wikia equivalents (like the thumbnail for the fish and its unique resource), I can track down the images for the thumbs

**Comment by GioGr** [comment]
fish
https://static.wikia.nocookie.net/warframe/images/d/dc/Lobotriscid.png
or
https://static.wikia.nocookie.net/warframe/images/d/dc/Lobotriscid.png/revision/latest/scale-to-width-down/39?cb=20201121032901

unique
https://static.wikia.nocookie.net/warframe/images/d/d9/ParasiticTethermaw64.png
or
https://static.wikia.nocookie.net/warframe/images/d/d9/ParasiticTethermaw64.png/revision/latest/scale-to-width-down/25?cb=20201124185358

**Comment by GioGr** [comment]
seems Flagellocanth missing also
```
  {
    "name": "Flagellocanth",
    "thumb": "qqqq",
    "wiki": "https://warframe.fandom.com/wiki/Flagellocanth",
    "unique": [{
      "name": "Ocular Stem-Root",
      "thumb": "qqqq",
      "wiki": "https://warframe.fandom.com/wiki/Ocular_Stem-Root"
    }],
    "location": "Surface",
    "time": {
      "string": "Any",
      "fass": {
        "appear": true,
        "prefer": false
      },
      "vome": {
        "appear": true,
        "prefer": false
      }
    },
    "rarity": "3-Rare",
    "hotspot": true,
    "bait": {
      "name": "Processed Fass Residue",
      "thumb": "fass",
      "recommended":true
    },
    "spear": {
      "spari": true,
      "ebisu": true
    },
    "maximumMass": "16kg",
    "small": {
      "resources": {
        "tumor": 3,
        "bladder": 3
      }
    },
    "medium": {
      "resources": {
        "tumor": 5,
        "bladder": 5
      }
    },
    "large": {
      "resources": {
        "tumor": 8,
        "bladder": 6
      }
    }
  },
```
unique 
https://static.wikia.nocookie.net/warframe/images/f/f4/OcularStem-Root64.png/revision/latest/scale-to-width-down/25?cb=20201124185010

fish

https://static.wikia.nocookie.net/warframe/images/6/6e/Flagellocanth.png/revision/latest/scale-to-width-down/39?cb=20201121032903

--------------------

Myxostomata > unique > wiki link missing underscore and has space instead

--------------------

Amniophysi Maximum Weight: 16 kg
Barbisteo Maximum Weight: 16 kg
Cryptosuctus Maximum Weight: 16 kg
Glutinox Maximum Weight: 16 kg
Kymaeros Maximum Weight: 16 kg

these 6 have their max weight on wiki
