### ISSUE TITLE
Add sound effects to certain events

### ISSUE THREAD

**Issue by Erlite** [WFCD/warframe-hub#50]
### Warframe Hub Issue
---
---

**Summary (short):**
Add sound effects for Cetus and Earth day/night cycles changing (seperate sfx for each).
---
**Description:**
- Cetus Day/Night: Sound 1 plays for Sunrise, Sound 2 plays for Sunset
- same thing for the general Earth day/night cycle
- Play a Baro audio quote when Baro arrives
---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [X] Suggestion

**Comment by Erlite** [comment]
Submitted by SasoDuck on the WFCD Discord.

**Comment by TobiTenno** [comment]
hmmmm... why? i guess it just seems like an odd thing to do

**Comment by MainlandHero** [comment]
@TobiTenno I mean Deathmax does have a way to notify the user when there's a new alert or invasion. We can extend that to all of the functionality I guess, but we can stow it away in a place that's out of sight and out of mind.

**Comment by TobiTenno** [comment]
like, i'm not arguing that it could be useful for someone, i'm more just asking for clarification and a fully fledged thoughtout thing

**Comment by lostguru** [comment]
A sunset audio prompt is useful for people doing eidolon hunts. [Clock of Eidolon](https://clockofeidolon.com/) uses one and it comes in handy; you just keep a separate tab of the website open and when you hear the eidolon roar, you know it's nighttime.

I imagine a sunset as well as a sunrise audio cue would also be useful for anyone who needs to do fishing out on the plains, since certain fish only spawn during the day or night.

**Comment by TobiTenno** [comment]
My thoughts, if we do them:
- Eidolon Roar for nighttime
- Simple Drum beat for Daytime
- Drop pickpup sound for alerts/other stuff if we want them

I'm just sharing thoughts, but I've got my own problems getting stuff implemented over on [wfcd/genesis](https://github.com/wfcd/genesis)

**Comment by MainlandHero** [comment]
@TobiTenno @lostguru I support this idea, but I would like to audio file for the eidolon roar as well as the classic warframe drum beat. Preferrably 1-2 seconds.

And yeah, finals are coming up, can't really support this until after Christmas/January

**Comment by TobiTenno** [comment]
[Drum hit](https://digitalextremesltd.app.box.com/s/vh2u41yhdlgp3girffucbynadoi33173/file/74341780574)
[General Tone (not drop pickup, but the old ship ping)](https://digitalextremesltd.app.box.com/s/vh2u41yhdlgp3girffucbynadoi33173/file/74341773390)

**Comment by MainlandHero** [comment]
I don't have access to those, gives me a 404 error @TobiTenno

**Comment by TobiTenno** [comment]
they're in the warframe fansite kit, i'll find better links

**Comment by TobiTenno** [comment]
[Navigate to Fansite Kit](https://digitalextremesltd.app.box.com/s/vh2u41yhdlgp3girffucbynadoi33173) > Ringtones > Android
Download TextMessage_SingleDrumHit.mp3 and TextMessage_ShipPagerDing.mp3

**Comment by Reidmaster** [comment]
I can possibly look into this.

**Comment by TobiTenno** [comment]
Added for alerts, invasions, and eidolon night begin.
