### ISSUE TITLE
[Bug]: Myxostomata requires hotspot, Processed bait icons wrong

### ISSUE THREAD

**Issue by GioGr** [WFCD/warframe-hub#515]
### Summary

tried fishing it without hotspot got 0 then hotspot spawned where i was and i got some, wiki also says it requires hotspot

these affect all fish that require those baits
Processed Vome Residue has wrong icon
https://static.wikia.nocookie.net/warframe/images/f/f0/ProcessedVomeResidue.png/revision/latest/scale-to-width-down/80?cb=20200915063058
Processed Fass Residue has wrong icon also
https://static.wikia.nocookie.net/warframe/images/4/4d/ProcessedFassResidue.png/revision/latest/scale-to-width-down/80?cb=20200915063056

### Version

old-hub (Default)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
your images don't work...

also, i think i have the wrong default in the form, but that's not your problem.

when we wrote the fish page, the images didn't exist yet, sadly.

**Comment by TobiTenno** [comment]
TODO: 
- [x] bcc43ca update Myxostomata to require hotspot
- [x] bcc43ca update vome residue icon
- [x] bcc43ca update processed fass residue icon

**Comment by TobiTenno** [comment]
also, bit of irony. I had the field set to true for myxostomata... but i had the wrong spelling on the name of the field 😅

**Comment by TobiTenno** [comment]
possibly fixed in [v1.0.3](https://github.com/WFCD/warframe-hub/releases/tag/v1.0.3)
could you check if the latest changes are adequate? I wanna make sure I didn't miss anything before I close

you may need to <btn>Ctrl</btn> + <btn>Shift</btn> + <btn>R</btn>

**Comment by GioGr** [comment]
they seem fine now
