### ISSUE TITLE
[Feature]: Update notification settings.

### ISSUE THREAD

**Issue by Everspace** [WFCD/warframe-hub#522]
### What would you like to see happen?

I would be nice if the Notifications for events were more "correct" and "granular"

Currently there's a lot of... extra stuff? Or the way to organize this all is very hard to use.

Things not on events really:
- Vauban parts
- Nitain

Things that would be useful:
- Specific parts you're waiting for for XYZ weapons.
- Full Fieldrons/Mutagen Mass (!!)/Detonite Ampule
- Category organization subheaders for
   - Arbitration
   - Lith/Meso/Neo/Axi/Requiem Fissures

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
I can look at removing the excess ones, however specific parts isn't going to happen, I'll mention that up front. That'll take excessive amounts of maintenance to add new ones every time they add a parted weapon.

The full ones are already in there, their labels just cover both samples and the full items.

I'll look at categorizing subheaders, but we already have to manually build a lot of that out, and it's rather messy no matter how we do it.

**Comment by TobiTenno** [comment]
just for a preview, this is the way i'm going. should make it easier to at least group them... somewhat.

![image](https://user-images.githubusercontent.com/7128721/126936744-5e20f9b3-dc00-4664-9c1b-747b1eafcab3.png)

**Comment by Everspace** [comment]
I wonder if that can be automated somewhat, or with minimal configuration? Like some JSON that is

```
[
  "Snipetron Vandal",
  "Dera Vandal"
]
```
And then the list is populated dynamically based on that information (Grab related Blueprint by Name, or all parts by English name?) and then updating can be done once every 6 months when they add a new thing.

**Comment by TobiTenno** [comment]
I'm not ready to commit to that yet, but I've made progress on the rest...

![image](https://user-images.githubusercontent.com/7128721/126942855-effed6d3-b575-4558-b1ee-c9242171a3e2.png)

**Comment by TobiTenno** [comment]
Feel free to try it out here: https://warframe-hub-git-better-rivens-wfcd.vercel.app/

**Comment by Everspace** [comment]
I think that's a good compromise for now, and a lot more usable on first blush. 

However the fieldron looks a bit funny
![image](https://user-images.githubusercontent.com/7560635/126943579-f2ff2c39-ff47-4ec1-a6b8-2ca598c0e51c.png)

**Comment by TobiTenno** [comment]
yeah, the problem is fieldron is fieldron and fieldron sample, but all other clan resources have a separate suffix
