### ISSUE TITLE
[Feature]: System preferred locale support

### ISSUE THREAD

**Issue by alexkoala** [WFCD/warframe-hub#531]
### What would you like to see happen?

example: https://holodex.net ([HolodexNet/Holodex](https://github.com/HolodexNet/Holodex))

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
That literally doesn't tell us anything.... please be more precise.

**Comment by TobiTenno** [comment]
What specifically are you wanting us to default to on initial site load, as the closest I've found thus far (`navigator.language`) does not globally get updated based on user preferences, from what i'm reading.

**Comment by TobiTenno** [comment]
I've implemented it over on #532, please let me know if that suffices for what you want, or if you're looking for deeper support than that

**Comment by alexkoala** [comment]
Yes. #532 is the feature what I want.
