### ISSUE TITLE
[Feature]: Add Deimos/Fortuna Cycle as Notification target

### ISSUE THREAD

**Issue by MrDj200** [WFCD/warframe-hub#548]
### What would you like to see happen?

The Desktop Notifications have both `Cetus' Day Start` and `Cetus' Day Start` as possible choices.
My feature request is that both Fortuna and Deimos Cycle changes are added.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
I'll definitely take a look

**Comment by TobiTenno** [comment]
closed with #552
