### ISSUE TITLE
Void Trader missing bottom line

### ISSUE THREAD

**Issue by MainlandHero** [WFCD/warframe-hub#55]
### Warframe Hub Issue
---
---

**Summary (short):**
---

Void trader is missing the bottom border.

**Description:**
---

This is caused when the void trader's inventory is empty, the element is hidden.
It does not need to be hidden as the element holds no content when the inventory is empty.

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

![image](https://user-images.githubusercontent.com/1594432/32928533-57810c1e-cb20-11e7-97c8-050e01f4090b.png)

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
fixed
