### ISSUE TITLE
[Feature]: Tenet Melee Weapons Rotation Timer and Types/Percentages

### ISSUE THREAD

**Issue by whbCool** [WFCD/warframe-hub#568]
### What would you like to see happen?

A window to display when the tenet melee weapons will rotate and what bonuses/percentages are currently available.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
Sorry, can't happen. DE doesn't provide the data anywhere for what bonuses/percentages are available, so we'd be changing a data store manually every ~4 days.
