### ISSUE TITLE
Collapse Invasions if more than 5, and add button to expand the rest

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#59]
### Warframe Hub Issue
---
---

**Summary (short):** Hide invasions if there are more than 5

---
**Description:** This would save space and make sure users know there's more below.
I don't know how we'd implement it, precisely, but it'd be _fantastic_

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by Tithen-Firion** [comment]
Just dropping bits of code that will help:
`$('#invasionList > li.list-group-item-borderless:nth-child(n+6)').slideToggle()` (or `slideUp` and `slideDown`)

Of course you also need to show invasions that are hidden after one of 5 visible ones ends:
`$('#invasionList > li.list-group-item-borderless:nth-child(-n+5)').show()`

**Comment by TobiTenno** [comment]
if you wanna make a quick pull just to see how it looks, i'll happily review it really quick and see how it looks. i'll add you to the org so it'll make a build for you

**Comment by EricSihaoLin** [comment]
I'm rethinking this, would a scrollable panel work?
The only problem is, how would the user know it is a scrollable area?

**Comment by dsinn** [comment]
If the scrollbar is visible, it may be okay.  Having a faded effect when you're not at the end of the content could also help, although I don't have the CSS savvy for the implementation details.

**Comment by 107g** [comment]
Hello there,

I just digged up that issue. I'm trying to implement that feature by reusing the 'Collapsible' component used for Bounties.

**Comment by TobiTenno** [comment]
I look forward to seeing what you do with it
