### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by EricSihaoLin** [WFCD/warframe-hub#63]
### Warframe Hub Issue
---
---

**Summary (short):**
---

Suggested by AJman14, Retro theme

**Description:**
---

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

![image](https://user-images.githubusercontent.com/1594432/33162040-676b29a0-cff5-11e7-8373-982ea7a6a0b5.png)

(Check one)
- [ ] Issue
- [X] Suggestion

**Comment by TobiTenno** [comment]
Use [Hack](https://github.com/source-foundry/Hack)?

**Comment by MainlandHero** [comment]
@TobiTenno I messaged AJman for a typography update, because that font is awful for readability.

**Comment by TobiTenno** [comment]
yeah, i'd prefer hack, it's probably the best monospace i've seen/used

**Comment by MainlandHero** [comment]
Possible contender for a more retro feel: [Telegrama Raw](https://www.fontsquirrel.com/fonts/telegrama)

**Comment by TobiTenno** [comment]
Almost feels _too_ retro... like, a little retro i get, but i also would want retro and readable

**Comment by AJman14** [comment]
It is a bit hard to read, but any 7-segment displays would be, naturally. I [brightened the timers](https://i.gyazo.com/d23c9fb87a48cb4c2e4d4774a462a565.png), so it helped a little with readability.

[Unibody 8](https://www.fontsquirrel.com/fonts/Unibody-8?q%5Bterm%5D=LED&q%5Bsearch_check%5D=Y) could work, if you still don't like it.

**Comment by AJman14** [comment]
Also, it is easier to read them when the timers are running, because the S would remain the same, when the "seconds" number is constantly changing.
