### ISSUE TITLE
[Feature]: Consolidate How To Fish Pages

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#631]
### What would you like to see happen?

We should consolidate the 2 fishing pages and use cards where information diverges (ala wiki?)

maybe turn this into the template for a type of blog post format?

Additional bits we need to make sure to mention:
- Using Oxylus will show an indicator on the mini-map in the shape of a goldfhish

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kastleghost** [comment]
Would also be nice to see preferred Warframes that are least distracted by enemies i.e. Ivara.  One of the most annoying things is constantly having to swap off fishing to attack an enemy that keeps hitting me.
