### ISSUE TITLE
[Bug]: No toggles on open area maps 

### ISSUE THREAD

**Issue by GioGr** [WFCD/warframe-hub#658]
### Summary

before when i was opening a map i was able to toggle  fishing spots etc but now i cant do aything and just see a blank version of the map,

tried at chrome and firefox no change
edit: both maps do this
![image](https://user-images.githubusercontent.com/12425911/146366906-17bdfe06-518c-4700-9bcb-725ddfa1f24d.png)

### Version

hub (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
looks like the mapping for the toggles didn't happen when we moved it over.

if you have logs from your browser, please provide them
