### ISSUE TITLE
Fissure Timer Issue

### ISSUE THREAD

**Issue by EricSihaoLin** [WFCD/warframe-hub#66]
### Warframe Hub Issue
---
---

**Summary (short):**
---

main.js:1 Uncaught TypeError: Cannot read property 'includes' of undefined
    at updateTimeBadges (main.js:1)

**Description:**
---

Cause: default:(e.attr("id").includes("alerttimer")||e.attr("id").includes("fissuretimer"))&&e.parent()[0].remove()}

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

(Check one)
- [X] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
I think this got cleared up already, but i'm adding a fix for it in #70

**Comment by TobiTenno** [comment]
fixed with #70
