### ISSUE TITLE
Alert/invasion reward filtering and notification

### ISSUE THREAD

**Issue by Tithen-Firion** [WFCD/warframe-hub#67]
### Warframe Hub Issue
---
---

**Summary (short):**
Add option to filter out alert/invasion rewards and notify user about new ones.
---
**Description:**
- Add alert/invasion filtering similar to [RaidTime](https://raidtime.net/en/game/tool/warframe/alarm)
  - settings stored in `localStorage`?
- Add sound/text notification to alerts/invasions not filtered out.

Related: #50 

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
settings would probably get stored in the cookie like they are for other parts...

**Comment by Tithen-Firion** [comment]
Isn't `localStorage` better? You can store more data there and it has no expiration date.

**Comment by TobiTenno** [comment]
considering the extremely tiny amount we store, i don't know that it's necessary right now

**Comment by TobiTenno** [comment]
Done
