### ISSUE TITLE
🐛 Icon for Tubercular Gill System is wrong

### ISSUE THREAD

**Issue by Ophyx** [WFCD/warframe-hub#670]
### Summary

In the Cambion Drift fishing data, the icon chosen for the cut fish reagent Tubercular Gill System is currently using the same icon as Fermented Bladder. Switch the icon to the correct icon so it's easier to see, which fish rewards which reagents when being cut.

### Version

hub (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
yup, definitely looks wrong

**Comment by TobiTenno** [comment]
I've updated the image and restarted the CDN, so it should be fixed... could you verify for me, @Ophyx, that it's working for you?

**Comment by TobiTenno** [comment]
probably fixed with https://github.com/WFCD/genesis-assets/commit/1131d527894088ea8141a5a859cd85e569ea8b40

**Comment by TobiTenno** [comment]
I've checked on another machine and it's working for me. closing.
