### ISSUE TITLE
Unexpected behavior of drag and drop

### ISSUE THREAD

**Issue by Tithen-Firion** [WFCD/warframe-hub#73]
### Warframe Hub Issue
---
---

**Summary (short):**
Customizing layout with drag and drop doesn't work as intended.

---
**Description:**
Components move in unexpected manner, you can't place them where you want. As shown in video below.

---
**If issue, Reproduction:**
In Firefox, move *Earth Cycle* component under *Cetus Cycle*.

---
**Mockups, screenshots, evidence:**
https://streamable.com/jq6ic

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
fixed with #77
