### ISSUE TITLE
:bug: synthesis is sometimes in the wrong language

### ISSUE THREAD

**Issue by Oakmontowls** [WFCD/warframe-hub#771]
### Summary

The page for synthesis targets is in the wrong language periodically. I have checked the language settings and they are set to english. Interestingly clearing the cache/cookies for the site does nothing, but opening the page in incognito mode does.
![image](https://user-images.githubusercontent.com/27376850/165885611-a376fe76-8daf-4339-93ab-85ecbe8ade2e.png)

### Version

hub (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
thanks for the report, it's likely part of the data caching on the api. I'll get it figured out at some point.

**Comment by TobiTenno** [comment]
Oh wait, incognito fixes it.... You might check your language settings, maybe?

**Comment by Oakmontowls** [comment]
I checked the language settings in warframe hub and they are set to English, is there another setting I should be looking at?

**Comment by TobiTenno** [comment]
> I checked the language settings in warframe hub and they are set to English, is there another setting I should be looking at?

Nope, just that one.

**Comment by TobiTenno** [comment]
If you're familiar with doing so, and you wouldn't mind looking for calls to api.warframestat.us/synthTargets and checking the request language and response language headers, that'd be great, but it might be hit and miss.

**Comment by Oakmontowls** [comment]
I'm not sure how to do that but if you link me to a guide I can try

**Comment by TobiTenno** [comment]
- Open DevTools (usually `Ctrl`+`Shift`+`I`)
- Navigate to "Network"
- ![image](https://user-images.githubusercontent.com/7128721/166082648-c839595d-a857-40cc-8c6e-c15644c0bebb.png)
- Filter by "synth"
- If nothing shows
	- navigate to "Application"
	- Click "Clear Site Data"
	- ![image](https://user-images.githubusercontent.com/7128721/166082723-a63f93d6-93f9-4396-8ea5-98ea44c58606.png)
	- Should be about in the middle of the screen, the only real button apart from the checkboxes
	- Then go back to Network and do a hard refresh (`Ctrl`+`Shift`+`R`)
	- Filter by synth
- Click "synthTargets"
- ![image](https://user-images.githubusercontent.com/7128721/166082797-59a0e25d-b238-43e3-bc12-f3e625f45e46.png)
- Screenshot (and post here) Request Headers and Response Headers
- ![image](https://user-images.githubusercontent.com/7128721/166082854-a4af17e4-4760-42ef-ba2e-9baa4d91ed9a.png)
- ![image](https://user-images.githubusercontent.com/7128721/166082885-76cc706d-0bcd-40fe-b9b7-9bfddc937a97.png)

For Request headers, as long as you get the "accept-language" header, that's primarily what i need.
For Response headers, as long as you get "content-language", that's primarily what i need

**Comment by Oakmontowls** [comment]
![image](https://user-images.githubusercontent.com/27376850/166088294-7775c771-a0ef-4163-9d91-0808bf3eb5ef.png)
![image](https://user-images.githubusercontent.com/27376850/166088318-e8094317-6cdf-469c-bff1-5173113999f4.png)
It's currently in English but when I change the language to something else (Italian) It doesn't switch for the synthesis page and in the request headers it still has the same accept-language en-US with nothing about language in the response headers 
![image](https://user-images.githubusercontent.com/27376850/166088422-e53cedda-ffc7-4d37-880e-be02d4103e3f.png)
![image](https://user-images.githubusercontent.com/27376850/166088433-e55cf3aa-2956-4378-aad0-718aa306f6a5.png)

**Comment by Oakmontowls** [comment]
Also the page is currently displaying in English

**Comment by TobiTenno** [comment]
ah, i'll definitely have to fix that. yeah, i'm guessing it's not really defaulting properly on the request & reply. i'll keep this open and work on it. thanks!

**Comment by TobiTenno** [comment]
yo! is it working properly more consistently now?

**Comment by Oakmontowls** [comment]
Well it's not loading at all for me right now.

**Comment by TobiTenno** [comment]
ah, i put in a fix for that as well, not sure why it's taking so long for updates to pull in on hub :hankey:

**Comment by TobiTenno** [comment]
please check it out now, you may need to do a hard refresh to get the updated content.

**Comment by Oakmontowls** [comment]
So it's working again but it isn't quite respecting the language option. In particular the names of the enemy is not getting translated when you change the language.

**Comment by TobiTenno** [comment]
i'll be honest, i think that's a shortcoming of the translation, not of hub. if you send me which language you're looking at, i'll check the data.

**Comment by Oakmontowls** [comment]
So just in just testing the languages "Italiano", "Čeština", and "Srpski" just default to English. As for the names not being translated, I noticed that the times the names were translated the image breaks like the entirety of the Chinese setting.
![image](https://user-images.githubusercontent.com/27376850/172062029-264e3543-6766-4747-8fd6-ae1d6eb1dd1f.png)
And then oddly other languages like Korean have a few translated names which also results in the broken images.
![image](https://user-images.githubusercontent.com/27376850/172062077-a7b6afb8-c0de-46d6-845c-c26fb5a8a3bb.png)

**Comment by TobiTenno** [comment]
yes, i believe the chinese one incorrectly translated some image names. as for italian, czech  and serbian, they are untranslated. if you're interested in translating for whichever language you need to leverage.

**Comment by Oakmontowls** [comment]
Yea none of those languages are ones I'd use I was just letting you know what is and isn't working.

**Comment by TobiTenno** [comment]
i have some fixes that should avoid the name causing bad images in a bit, but that'll be separate. thanks for looking and testing!

**Comment by TobiTenno** [comment]
fixed with a2259f78d6455275729e3e511f94ec6344225631
