### ISSUE TITLE
:bug: "Lu-yan" isn't shown as "survival" in void storms

### ISSUE THREAD

**Issue by nammerduong** [WFCD/warframe-hub#772]
### Summary

For some reason Lu-yan is listed as volatile on the website. Please change it to survival.

### Version

hub (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
It was probably a volatile before, please be patient after updates as sometimes the mission types change after updates
