### ISSUE TITLE
:bug: Cetus Timer not matching game

### ISSUE THREAD

**Issue by Nikobawzz** [WFCD/warframe-hub#784]
### Summary

hello there, the cetus tracker is wrong, cause they have changed it to 1 hour day and 1 hour night now, just wonder if you guys can change it! thanks in advance!

### Version

hub (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SlayerOrnstein** [comment]
When did they announce this?

**Comment by Nikobawzz** [comment]
I’m pretty sure it came with the new update, cause the night cycle used to be 45mins but now is 1h, and day is 1h as well, I noticed the change since I’ve recently started doing eidolon runs, so the night cycle now is longer then it used to be and the day is a tad shorter then before

**Comment by SlayerOrnstein** [comment]
Night just came up and it's still 50 minutes.

**Comment by TobiTenno** [comment]
Yeah, I'm gonna hard press doubt, I haven't seen any evidence for this actually changing, and we use the same timer across all of the services that consume the same API

**Comment by Nikobawzz** [comment]
Here’s a screenshot, I just logged in as it said 1h:37mins on the warframe hub timer and in-game it says 1h until night time

**Comment by TobiTenno** [comment]
the game says 1h until it's vastly less than 1h. it's said 1h for the last 20 minutes.  (also, there's no screenshot in your post)

**Comment by Nikobawzz** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TobiTenno** [comment]
still nothing. also, now, 23 minutes in, it still says 1 hour till night ingame.

**Comment by TobiTenno** [comment]
![image](https://user-images.githubusercontent.com/7128721/168455603-bd6b1853-badd-4af2-aabb-a90143e321a2.png)

at the same time in-game says 59 minutes, hub says 59 minutes

**Comment by SlayerOrnstein** [comment]
It's the same for the Warframe Nexus app, I doubt that they would make a change like that without updating the app.

**Comment by Nikobawzz** [comment]
Hmm, that’s weird, then something must be wrong on my timer maybe, cause for me when it becomes night it always says “ day in 1h “ , and same thing on the day cycle

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
