### ISSUE TITLE
Wrong Relics stated in all Bountys that reward the NEW Zephyr & Chroma Prime Relics :bug: 

### ISSUE THREAD

**Issue by HubBrot** [WFCD/warframe-hub#785]
### Summary

hub.warframestat.us - Wrong Relics stated in all Bountys that reward the NEW Zephyr & Chroma Prime Relics
drops.warframestat.us They also do not show up on drops page.

Relics are:

Lith C8, Lith T6, Meso R4, Neo K3, Neo Z8 and Axi G5.

### Version

hub (Default)

### What browsers are you seeing the problem on?

Opera

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
can you please screenshot so we can match up which bounties it showed? we're given the bounty reward table from the worldstate data and we use that to determine the search from drops.warframestat.us, so i'm not sure what you're referring to

**Comment by TobiTenno** [comment]
Oh, rereading what you wrote, its s simply that DE hasn't updated their drop tables or that they've not properly gotten parsed yet

**Comment by TobiTenno** [comment]
Based on a search of the drops, they've not updated the tables

**Comment by HubBrot** [comment]
So guess we have to wait for them to update?
When i checked the Changelog "https://www.warframe.com/de/updates/pc/31-5-9" found this passage:
"
Find their Relics in the Void or Bounty rewards starting now! 

Zephyr Prime, Chroma Prime, Tiberon Prime, Kronen Prime, Rubico Prime, and Gram Prime Relics have been added to the drop tables! These Relics have replaced the Banshee Prime and Mirage Prime Relics in the Void drop tables, Bounties, and Relic Packs. 
"

**Comment by TobiTenno** [comment]
https://www.warframe.com/droptables was last updated on May 2, before that update.
