### ISSUE TITLE
timers and all missions info are missing and keep reloading :bug: 

### ISSUE THREAD

**Issue by Psyqoo** [WFCD/warframe-hub#786]
### Summary

i try to check https://old-hub.warframestat.us/# or https://hub.warframestat.us/#/ 
but i cant see anything, like open-world times, void fissures missions, new, ...etc 
everything is keep loading for ever , am not sure if this is on my network or something else but my connection is ok and working fine 
![chrome_5S9duZVAT6](https://user-images.githubusercontent.com/50375719/168876876-ce80fdd6-0889-423a-8957-487c394712f5.png)
![chrome_bNys8w0w71](https://user-images.githubusercontent.com/50375719/168876947-a5f929ef-e659-4fc6-b211-b3226d3c5ced.png)

### Version

old-hub (Legacy)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
yes, there's an api issue with the worldstate not loading. you'll have to wait until it's remediated.

**Comment by TobiTenno** [comment]
@Psyqoo should be fixed, can you confirm?

**Comment by TobiTenno** [comment]
ok, i'm closing.
