### ISSUE TITLE
:bug:  Status Page shows default Nginx Webpage

### ISSUE THREAD

**Issue by Serverfrog** [WFCD/warframe-hub#788]
### Summary

The Link on the top Ribbon Menu for Status which is then located under https://warframestat.us/ just shows the Default Nginx Website

### Version

hub (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Brave

### Relevant log output

```shell
Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
which link that you mentioned? could you screenshot it? I probably need to remove the link.

**Comment by Serverfrog** [comment]
Sure.
![image](https://user-images.githubusercontent.com/1306404/170314539-2faed018-93fd-4081-8c3e-5d65d4aa048c.png)

Under Projects -> Status

Which i think should be the Status of Warframe etc ;)

**Comment by TobiTenno** [comment]
thanks! it was for a time. I'm gonna change it to our status page from uptimerobot, as the status page we had been using (from cachet) basically destroyed itself and uptimerobot is a bit cleaner

**Comment by Serverfrog** [comment]
That makes sense ;) Maybe a 304 instead of the Default page to the Uptimerobot variant?

**Comment by TobiTenno** [comment]
that's a great option. i'm also going to look at routing the main page to the uptime robot variant via CNAME so it's just the right place right away

**Comment by TobiTenno** [comment]
oooof, looks like my way requires more payment, so we're going your way!

**Comment by Serverfrog** [comment]
Good to know xD I only worked with things like cloudflare where this would not be a Problem as far as i know. But still the 304 solution works... i mean even google uses that :P

**Comment by TobiTenno** [comment]
for sure. we use cloudflare, but i'm out of pagerules, so all through nginx instead

**Comment by Serverfrog** [comment]
Ahh you use the Pagerules. i never worked with them. I just would try to add it in the DNS settings itself. But well: go the path of least resistance, and a little config change on the nginx to redirect them is pretty fast ;)

**Comment by TobiTenno** [comment]
unfortunately nginx didn't let me specify 304, but 301 worked. how do you do the 304/redirect with the DNS settings itself? not seen that before.

**Comment by Serverfrog** [comment]
My bad... it should be 301. 304 would be `Not Modified`... which just wrong xD

**Comment by TobiTenno** [comment]
gotcha, how do you do the 301 from dns settings, then? cause that makes well enough sense to me, just curious how you get it to do it.

**Comment by Serverfrog** [comment]
Good Question. As far as i see that is something that is not normaly done over DNS (i though it was possible because it sounded from your side like it was) but something Providers will add in different ways...
Cloudflare's solution is Page Rules. So no lock without moar money

One way i see, but i am not confident enough to say: fiddle around with it (i hate DNS and cry everytime i need to touch it myself) is an CNAME entry with `@` as name and then the Uptimerobot address as value. But i think that would just change the base address and you can't add the full path to that specific dashboard to it

**Comment by TobiTenno** [comment]
yeah, that's essentially how you set up the redirect if you're paying their extra service cost, but you're right, and doing that without the extra service just gives ssl errors, sadly.

regardless, got it set up, thanks for the thoughts and insights, it's fixed now
