### ISSUE TITLE
:bug: Synthesis data is not appearing on the site

### ISSUE THREAD

**Issue by Janitsu** [WFCD/warframe-hub#792]
### Summary

After a few seconds, the banner at the top disappears and this screen remains empty. I have tried disabling uBlock origin as well as Firefox enhanced protection to no avail. Tried on Edge, and seems to be an issue regardless of browser.

![image](https://user-images.githubusercontent.com/8763688/171290157-58cce5d7-63ab-407b-899f-33f061f019ff.png)

### Version

hub (Default)

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
already discussed in #771, there's issues with the cache refreshing

**Comment by TobiTenno** [comment]
please check it out now, you may need to do a hard refresh to get the updated content.

**Comment by TobiTenno** [comment]
fixed with a2259f78d6455275729e3e511f94ec6344225631 and a46f73da39b8123ab0822b405d52d92d0f0a6f9b
