### ISSUE TITLE
Feature request: Display K-drive race titles :rocket: 

### ISSUE THREAD

**Issue by Strykar** [WFCD/warframe-hub#798]
### What would you like to see happen?

Display the names of the K Drive races in the Vallis and Deimos.
At the minimum show the races which drop parts for the Infested K-drive, [Feverspine](https://warframe.fandom.com/wiki/K-Drive_Race#Races).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
well, as much as we'd love to, they're randomly generated at a resetting interval, with no data from DE on when or which races there are.
Would you like to have all of them, or just the active ones?
I think the former would be technically possible, it'd just take some time.

**Comment by Strykar** [comment]
I thought we could pull the current active races?

**Comment by TobiTenno** [comment]
where from?

**Comment by TobiTenno** [comment]
I'd love to, i've just never found a consumeable location
