### ISSUE TITLE
:rocket: Ergo Glast offerings timer

### ISSUE THREAD

**Issue by Janitsu** [WFCD/warframe-hub#804]
### What would you like to see happen?

There could be a cycle timer (or a new component) that shows the Ergo Glast timer. Ergo Glast gets new items every 4 days at precisely 0.00 UTC. Right now, there is a timer on the wiki site, but it would be really handy to see all the timers in one place.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
dupe #568
