### ISSUE TITLE
warframe hub shows in russian language :bug: 

### ISSUE THREAD

**Issue by Psyqoo** [WFCD/warframe-hub#808]
### Summary

both https://hub.warframestat.us/ and https://old-hub.warframestat.us/# shows to me in what looks like Russian language although i never changed the language to Russian and my pc system uses English only 
i tried to refresh the webpage many times and even ctrl+f5 +cleared all cash and cookies but same issue 
but I noticed that if i left the tap open for like 10 to 15 minutes it will change to English , sometimes all of the page and sometimes some parts of it like sorti and void fissures but the news and invasions are still in Russian lang 
i have screenshoots of old-hub in Russian lang but i can't post hub.warframe because right now it turned to English and i can't reproduce the bug to show it in russian for now but am sure it will came back to russian as i have been faced this issue for weeks now 
![chrome_46YPRCToAY](https://user-images.githubusercontent.com/50375719/174672335-b3731bc0-be5c-4ea5-ac3e-a27d62762d98.png)
![chrome_eKwL4HTfAh](https://user-images.githubusercontent.com/50375719/174672356-f0ef7ce8-1199-4c14-a21c-c20bb423bd1c.png)

### Version

old-hub (Legacy)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
this is probably because old-hub is, as the name mentions, woefully outdated and won't be updated, so... that's not gonna be changed. I'm not aware of anything missing on current hub that old-hub had, apart from moving components, which is not ever planned to happen.
