### ISSUE TITLE
Mobile Weirdness

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#81]
### Warframe Hub Issue
---
---

**Summary (short):** Columns too narrow, component labels not visible

---
**If issue, Reproduction:** View on a mobile device

---
**Mockups, screenshots, evidence:** 
![image](https://user-images.githubusercontent.com/7128721/34884348-10852744-f782-11e7-8134-cdc2ba58bfc9.png) 
![screenshot_20180112-101946](https://user-images.githubusercontent.com/7128721/34884391-39900c58-f782-11e7-9ecd-4d79081605e8.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by EricSihaoLin** [comment]
@TobiTenno My initial suspicions are the labels that reside in the dropdown navigation. I have had problems with labels before.

**Comment by Tithen-Firion** [comment]
Columns width is Packery related problem.

**Comment by TobiTenno** [comment]
> tithen-firion
it's a packery problem

_nothing new here_
/s

@EricSihaoLin have you had any luck fixing them before?

**Comment by TobiTenno** [comment]
looking at it, i think we just need to do a better job telling mobile layouts to go full width. [w3 schools](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) has a good article on it in their mediaqueries page

**Comment by EricSihaoLin** [comment]
Yeah, the column width does not like the absolute modifier on position, so it refuses to resize to the correct width, but Packery requires the absolute tag for component placement.

The mobile dropdown is a css problem, it can be fixed. The dropdown is just not used to take in a label on a mobile configuration. All of the link based dropdown are anchors.

**Comment by TobiTenno** [comment]
ah. I can put in the mediaquery fix for the width. what are you thinking for the mobile dropdown? i'm not seeing it on chrome when i run it, only literally on phone.
