### ISSUE TITLE
:bug: Wrong mission type on Railjack Fissure

### ISSUE THREAD

**Issue by Drasiel** [WFCD/warframe-hub#817]
### Summary

Railjack node Orvin-Haarc (venus) Extermination | Lith is actually a spy mission

### Version

hub (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
thanks dras! on it.

**Comment by TobiTenno** [comment]
fix out on the api is up, hopefully it's visible soon, i know the fissure is probably long gone.
