### ISSUE TITLE
:bug: Site showing a white page on Firefox

### ISSUE THREAD

**Issue by VoidCnTL** [WFCD/warframe-hub#857]
### Summary

The site is not opening and basically shows a white page on Firefox. It is working fine on Chrome. I pasted the errors I found from Browser Console. 

### Version

hub (Default)

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 3 background.js:1
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 307"  data: no] 2 FaviconLoader.jsm:307:24
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
are you blocking anything with ublock, etc?
i ask because we have tests for firefox and they shouldn't pass if this would be such an issue on stock firefox

**Comment by VoidCnTL** [comment]
I tried with ublock off and I don't have anything else that would interfere with the site.

![image](https://user-images.githubusercontent.com/90516471/187984529-71ae76f9-1d37-420f-8d86-db8c8549fb09.png)

Point of note, I am using Firefox on Linux

**Comment by TobiTenno** [comment]
check your console log? our tests run on ubuntu, so shouldn't matter that it's on linux, and i run daily on linux

personally i blame KDE

could you also turn off your japanese translator (assuming my google fu is serving me well)

**Comment by VoidCnTL** [comment]
The extensions were disabled and I removed them anyways just to check. The issue persists. 

![image](https://user-images.githubusercontent.com/90516471/188256825-9a6cb62c-c3e9-4580-87a9-7a491ef415bd.png)
```

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. hub.warframestat.us
The script from “https://hub.warframestat.us/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. hub.warframestat.us
Uncaught SyntaxError: expected expression, got '<' rocket-loader.min.js:1
The resource at “https://hub.warframestat.us/js/app.c11bb3d0.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. hub.warframestat.us
The resource at “https://hub.warframestat.us/js/chunk-vendors.039b3055.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. hub.warframestat.us

```


Edit: Also I checked with Sway just in case and X11 version of Plasma, but the results seem to be same.

Edit 2: I tried building and running the development version on my machine and it seems to be opening just fine on Firefox, but the web version continues to show blank page.

![image](https://user-images.githubusercontent.com/90516471/188257319-1721d6ed-1ca6-40b2-a210-275aef9213ae.png)

**Comment by TobiTenno** [comment]
> Uncaught SyntaxError: expected expression, got '<' rocket-loader.min.js:1

this is the one i'd assume is the issue. could you try purging the application (but not local storage)?

I ask because i just loaded up the app (firefox 107, gnome, arch) and it's working as expected. i'm not 100% sure what's different between our environments. if you wouldn't mind terribly hopping on discord, i'd love to dig into it with you on a call if the cache wipe doesn't fix it

**Comment by VoidCnTL** [comment]
Clearing the site data for Warframe Hub solved the issue and it is working normally now. Thanks.
