### ISSUE TITLE
No icon for corrupted faction

### ISSUE THREAD

**Issue by Tithen-Firion** [WFCD/warframe-hub#86]
### Warframe Hub Issue
---
---

**Summary (short):** icon for sortie defaults to corpus because we don't have corrupted one

---
**Description:**

---
**If issue, Reproduction:** open hub today

---
**Mockups, screenshots, evidence:** 
![obraz](https://user-images.githubusercontent.com/10004135/35001916-4b8642f6-fae8-11e7-9323-35454e420463.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by TobiTenno** [comment]
I'll fix this with #80

**Comment by EricSihaoLin** [comment]
#80 has been merged.
