### ISSUE TITLE
:rocket: Fissure panel: Show if Steel Path Fissure or not

### ISSUE THREAD

**Issue by Lenzelot** [WFCD/warframe-hub#864]
### What would you like to see happen?

With the Warframe Update 32 Veilbreaker came Steel Path mode in Fissures. It would be cool if the Fissure panel in warframe hub would display if a node is Steel Path or not. Right now I don't think you can see the difference from the UI. Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
Its planned.

**Comment by Lenzelot** [comment]
Awesome, thank you guys. We appreciate your work.

**Comment by TobiTenno** [comment]
![image](https://user-images.githubusercontent.com/7128721/189550125-426997cc-1d70-431d-8cc4-ab4853f147fd.png)
thoughts, @Lenzelot?

**Comment by TobiTenno** [comment]
sorry it's zoomed a ton, it's just for the sake of showing the whole thing

**Comment by Lenzelot** [comment]
This is good when players looking for a specific fissure class, because its sorted after the tiers. I thought about alternatives, like adding another category etc. but I think this is comprehensive and gets the job done.
