### ISSUE TITLE
:bug: sound filters

### ISSUE THREAD

**Issue by migo3196** [WFCD/warframe-hub#882]
### Summary

> hmm can somebody help.. i cant turn on the sounds filters.. when i switch it on.. it will keep turned back off

After turning the switches on on sound filters, if I close and re-open the settings dialog, they are off again.

### Version

hub (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by migo3196** [comment]
any update for this ?

**Comment by TobiTenno** [comment]
not yet, i've been trying to stay caught up with all of the other bits to keep things running too. and as the labels mention, this is an inconvenient issue, but not breaking the whole site.

**Comment by TobiTenno** [comment]
well, it wasn't super hard to fix, it's just waiting for reviews
