### ISSUE TITLE
Daily reset timer off by at least 1 minute 30 seconds :bug: 

### ISSUE THREAD

**Issue by BlackAce21** [WFCD/warframe-hub#924]
### Summary

I just used the daily reset timer and it was off by at least a minute thirty and possibly more. Was trying to beat the timer to get some toroids in but ended up finishing with 3 minutes left on the hub timer and 1.5-2 minutes left when I went to turn in the toroids but the daily cap had already reset.

Not sure if this is something you are aware of and can't be made more accurate or not but I thought I would let you know it's a thing that exists.

### Version

hub (Default)

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
Unless your local system clock is off, I don't see how it would be.

**Comment by BlackAce21** [comment]
My local system clock was in fact off by 3 minutes. Didn't expect that. Would it be possible to add a check to local system time against a time server in the web page to help prevent issues like this in future? At minimum a warning that the timers are based off local system time and that it needs to be properly synced might not be a bad idea. I'm going to add a weekly sync task for my own system though. Apologies for wasting your time :)

:edit: plot twist, time sync was already scheduled and failing due to corrupted system files. woops xD

**Comment by TobiTenno** [comment]
:metal: it happens to all of us, i'll add a tooltip saying as much!

**Comment by TobiTenno** [comment]
@BlackAce21 i've got a PR up if you wanna take a look at the fix
