### ISSUE TITLE
Feature Request - Add Support for Saving "Components" selection on Timers page

### ISSUE THREAD

**Issue by Kraust** [WFCD/warframe-hub#97]
### Warframe Hub Issue
---
---

**Summary (short):**
Feature Request - Add Support for Saving "Components" selection on Timers page
---
**Description:**
Would be nice to be able to save the configuration of "Components" selected on the Timer's page. Can be done via cookies, local storage, what have you. I can probably do this if nobody is available.

---
**If issue, Reproduction:**
n/a

---
**Mockups, screenshots, evidence:**
n/a

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
it already does
