### ISSUE TITLE
Feature Request: Add timer to sortie component

### ISSUE THREAD

**Issue by thegreatersea** [WFCD/warframe-hub#99]
### Warframe Hub Issue
---

**Summary (short):**
I believe it would be helpful to add a timer to the sortie component, similar to the rollover and bounty timers.

---
**Description:**
Given that there are already timers for other, similar components (Darvo, Void Trader, Day/Night Cycles, etc.), I was wondering if it would be possible to add one to the sortie component as well?

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
Sure, i'm adding something for this shortly

**Comment by TobiTenno** [comment]
Done and Merged
